import type { ProductOffer } from "@/types/product";

/** Refills multimarca + accesorios Acquabios (páginas de catálogo posteriores). */
export const acquabiosExtraProducts: ProductOffer[] = [
  {
    id: "acquabios-refil-acqua-cs",
    name: "Refil Acqua CS Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Consul* — triple filtración",
    description:
      "Refil con triple filtración, alta eficiencia en reducción de cloro libre y retención de impurezas. Compatible con purificadores Consul*: CPC30AB, CPC30AF, CPB36AB, CPB36AF, CPB35AB, CPB35AF, CPB34AS, CPB34AF, CPB34AB, CPC31AF, CPC31AB. Código 1005-0046.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Consul*",
    badgeTone: "blue",
    note: "Código: 1005-0046",
    image: "/products/product-refil-acqua-cs.png",
    images: ["/products/product-refil-acqua-cs.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "40 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "2.500 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0046" },
      { label: "Caudal", value: "40 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "2.500 litros" },
    ],
    features: [
      "Triple filtración",
      "Compatible Consul*",
      "Reducción de cloro libre",
    ],
  },
  {
    id: "acquabios-refil-acqua-cs10",
    name: "Refil Acqua CS10 Acquabios",
    brand: "Acquabios",
    subtitle: "7 etapas + Multibac — Consul*",
    description:
      "Alta eficiencia con 7 etapas de purificación y acción bacteriológica Multibac. Clase A. Compatible Consul* CPB34AS/AF/AB, CPC31AF/AB; ultrafiltración en CPC30AB/AF, CPB35AB/AF, CPB36AB/AF. Código 1005-0056.",
    priceBefore: 0,
    priceNow: 0,
    badge: "7 etapas",
    badgeTone: "yellow",
    note: "Código: 1005-0056",
    image: "/products/product-refil-acqua-cs10.png",
    images: ["/products/product-refil-acqua-cs10.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "40 L/h", icon: "bottles" },
      { label: "Clase A", icon: "bolt" },
      { label: "2.500 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0056" },
      { label: "Caudal", value: "40 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase A (0,5 a 1 μm)",
      },
      { label: "Vida útil", value: "2.500 litros" },
      { label: "Tecnología", value: "Multibac · 7 etapas" },
    ],
    features: [
      "7× más filtración",
      "Acción bacteriológica Multibac",
      "Compatible Consul*",
    ],
  },
  {
    id: "acquabios-refil-acqualux-pe",
    name: "Refil Acqualux PE Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Electrolux* PE10B / PE10X",
    description:
      "Impide la proliferación de bacterias. Alta eficiencia en reducción de cloro libre y retención de impurezas. Compatible Electrolux* PE10B, PE10X. Código 1005-0051.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Electrolux*",
    badgeTone: "blue",
    note: "Código: 1005-0051",
    image: "/products/product-refil-acqualux-pe.png",
    images: ["/products/product-refil-acqualux-pe.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0051" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
      { label: "Compatibilidad", value: "Electrolux* PE10B, PE10X" },
    ],
    features: [
      "Antiproliferación bacteriana",
      "Reducción de cloro libre",
      "Compatible Electrolux*",
    ],
  },
  {
    id: "acquabios-refil-acqualux-g",
    name: "Refil Acqualux G Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Electrolux* PA21G / PA26G / PA31G",
    description:
      "Refil con triple filtración. Alta eficiencia en reducción de cloro libre y retención de impurezas. Compatible Electrolux* PA21G, PA26G, PA31G. Código 1005-0052.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Electrolux*",
    badgeTone: "blue",
    note: "Código: 1005-0052",
    image: "/products/product-refil-acqualux-g.png",
    images: ["/products/product-refil-acqualux-g.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase A", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0052" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase A (0,5 a 1 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
      {
        label: "Compatibilidad",
        value: "Electrolux* PA21G, PA26G, PA31G",
      },
    ],
    features: [
      "Triple filtración",
      "Clase A",
      "Compatible Electrolux*",
    ],
  },
  {
    id: "acquabios-refil-acqualux-pa",
    name: "Refil Acqualux PA Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Electrolux* PA10N / PA20–40G",
    description:
      "Refil compatible Electrolux* PA10N, PA20G, PA25G, PA30G, PA40G. Código 1005-0053.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Electrolux*",
    badgeTone: "blue",
    note: "Código: 1005-0053",
    image: "/products/product-refil-acqualux-pa.png",
    images: ["/products/product-refil-acqualux-pa.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0053" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
    ],
    features: ["Compatible Electrolux* línea PA"],
  },
  {
    id: "acquabios-refil-acqualux-pc",
    name: "Refil Acqualux PC-PH-PE Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Electrolux* PC41 / PH41 / PE11 / Pure 4X",
    description:
      "Refil compatible Electrolux* PC41B/X, PH41B/X, PE11B/X, PURE 4X. Código 1005-0054.",
    priceBefore: 0,
    priceNow: 0,
    badge: "100 L/h",
    badgeTone: "yellow",
    note: "Código: 1005-0054",
    image: "/products/product-refil-acqualux-pc.png",
    images: ["/products/product-refil-acqualux-pc.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "100 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0054" },
      { label: "Caudal", value: "100 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
    ],
    features: ["Compatible Electrolux* PC/PH/PE/Pure 4X"],
  },
  {
    id: "acquabios-refil-acqualux-p4x",
    name: "Refil Acqualux P4X Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Electrolux* PE12 / PC01X",
    description:
      "Refil compatible Electrolux* PE12A/V/G/B y PC01X. Código 1005-0080.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Electrolux*",
    badgeTone: "blue",
    note: "Código: 1005-0080",
    image: "/products/product-refil-acqualux-p4x.png",
    images: ["/products/product-refil-acqualux-p4x.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "100 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0080" },
      { label: "Caudal", value: "100 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
    ],
    features: ["Compatible Electrolux* PE12 y PC01X"],
  },
  {
    id: "acquabios-refil-multiuso",
    name: "Refil Multiuso Acquabios",
    brand: "Acquabios",
    subtitle: "Polipropileno + carbón · rosca 1/2\"",
    description:
      "Fabricado en polipropileno y carbón activado con rosca 1/2\". Uso bajo pileta, bebederos, máquinas de hielo, jugos y café. Código 1005-0010.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Multiuso",
    badgeTone: "blue",
    note: "Código: 1005-0010",
    image: "/products/product-refil-multiuso.png",
    images: [
      "/products/product-refil-multiuso.png",
      "/products/product-refil-multiuso-contexto.png",
    ],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "6.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0010" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "6.000 litros" },
      { label: "Rosca", value: "1/2\"" },
    ],
    features: [
      "Uso bajo pileta y equipos de consumo",
      "Rosca estándar 1/2\"",
      "Larga vida útil 6.000 L",
    ],
  },
  {
    id: "acquabios-refil-multiuso-pre",
    name: "Refil Multiuso Pré Acquabios",
    brand: "Acquabios",
    subtitle: "Prefiltro — protege tu equipo",
    description:
      "Prefiltro que limpia el agua antes de entrar al equipo, alarga la vida del filtro principal y reduce mantenimiento. Código 1005-0011.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Pré",
    badgeTone: "yellow",
    note: "Código: 1005-0011",
    image: "/products/product-refil-multiuso-pre.png",
    images: ["/products/product-refil-multiuso-pre.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "6.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0011" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "6.000 litros" },
    ],
    features: [
      "Protege el filtro principal",
      "Menos residuos en el equipo",
      "Menos mantenimiento",
    ],
  },
  {
    id: "acquabios-refil-abdl50",
    name: "Refil ABDL50 Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Pentair / Top Life Platinum",
    description:
      "Compatible con purificadores Pentair Galón Automático, Top Life Platinum y otros. Código 1005-0016.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1005-0016",
    image: "/products/product-refil-abdl50.png",
    images: ["/products/product-refil-abdl50.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "50 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "6.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0016" },
      { label: "Caudal", value: "50 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "6.000 litros" },
    ],
    features: ["Compatible Pentair y Top Life Platinum"],
  },
  {
    id: "acquabios-refil-ab1000-carbon",
    name: "Refil AB1000 Carbon Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Líder / Toplife",
    description:
      "Compatible con purificadores Líder y Toplife. Código 1005-0040.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1005-0040",
    image: "/products/product-refil-ab1000-carbon.png",
    images: ["/products/product-refil-ab1000-carbon.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "40 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
      { label: "1.500 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0040" },
      { label: "Caudal", value: "40 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Vida útil", value: "1.500 litros" },
    ],
    features: ["Compatible Líder y Toplife"],
  },
  {
    id: "acquabios-refil-pro-bl",
    name: "Refil Pro-BL Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Europa* Bliss",
    description:
      "Compatible con purificador Europa* Bliss. Código 1005-0119.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Europa*",
    badgeTone: "blue",
    note: "Código: 1005-0119",
    image: "/products/product-refil-pro-bl.png",
    images: ["/products/product-refil-pro-bl.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0119" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (≥ 5 a < 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
      { label: "Compatibilidad", value: "Europa* Bliss" },
    ],
    features: ["Compatible Europa* Bliss"],
  },
  {
    id: "acquabios-refil-pro-dv",
    name: "Refil Pro-DV Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible Europa* Da Vince / Fluir",
    description:
      "Compatible con purificadores Europa* Da Vince y Fluir. Código 1005-0120.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Europa*",
    badgeTone: "blue",
    note: "Código: 1005-0120",
    image: "/products/product-refil-pro-dv.png",
    images: ["/products/product-refil-pro-dv.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0120" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (≥ 5 a < 15 μm)",
      },
      { label: "Vida útil", value: "3.000 litros" },
      {
        label: "Compatibilidad",
        value: "Europa* Da Vince y Fluir",
      },
    ],
    features: ["Compatible Europa* Da Vince y Fluir"],
  },
  {
    id: "acquabios-refil-fitt",
    name: "Refil Purificador Fitt Acquabios",
    brand: "Acquabios",
    subtitle: "Alcalino · Pré · Ultrafiltración",
    description:
      "Línea Fitt Acquabios (entrada 1/4\"): Alcalino (1005-0134), Pré-filtración (1005-0135) y Ultrafiltración Clase A (1005-0136). 60 L/h, vida útil 2.700 litros.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Fitt",
    badgeTone: "blue",
    note: "Códigos: 1005-0134 / 1005-0135 / 1005-0136",
    image: "/products/product-refil-fitt-alcalino.png",
    images: [
      "/products/product-refil-fitt-alcalino.png",
      "/products/product-refil-fitt-pre.png",
      "/products/product-refil-fitt-ultra.png",
    ],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "2.700 L", icon: "bottles" },
      { label: "1/4\"", icon: "metal" },
    ],
    colors: [
      {
        name: "Alcalino",
        codes: "1005-0134",
        swatch: "#81c784",
        image: "/products/product-refil-fitt-alcalino.png",
      },
      {
        name: "Pré-filtración",
        codes: "1005-0135",
        swatch: "#8e6bb8",
        image: "/products/product-refil-fitt-pre.png",
      },
      {
        name: "Ultrafiltración",
        codes: "1005-0136",
        swatch: "#4fc3f7",
        image: "/products/product-refil-fitt-ultra.png",
      },
    ],
    characteristics: [
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Vida útil", value: "2.700 litros" },
      {
        label: "Alcalino / Pré",
        value: "Clase C (≥ 5 a < 15 μm)",
      },
      {
        label: "Ultrafiltración",
        value: "Clase A (≥ 0,5 a < 1 μm)",
      },
    ],
    features: [
      "Línea Fitt Acquabios",
      "Entrada 1/4\"",
      "Versión ultrafiltración Clase A",
    ],
  },
  {
    id: "acquabios-refil-pre-ab3",
    name: "Refil Pré AB3 Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible IBBL* PDF / Smart H2O",
    description:
      "Compatible IBBL* PDF100, PDF300, PDF300-2T, SMART H2O, PFN2000. Código 1005-0048.",
    priceBefore: 0,
    priceNow: 0,
    badge: "IBBL*",
    badgeTone: "blue",
    note: "Código: 1005-0048",
    image: "/products/product-refil-pre-ab3.png",
    images: ["/products/product-refil-pre-ab3.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "4.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0048" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "4.000 litros" },
    ],
    features: ["Compatible IBBL* bebederos PDF / Smart H2O"],
  },
  {
    id: "acquabios-refil-ab3-natural",
    name: "Refil AB3 Natural Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible IBBL* FR600 / Immaginare / Evolux",
    description:
      "Compatible IBBL* FR600 Speciale/Exclusive/Expert, FRQ600, PFN, Classlantis, PDF, Immaginare, Evolux. Código 1005-0045.",
    priceBefore: 0,
    priceNow: 0,
    badge: "IBBL*",
    badgeTone: "blue",
    note: "Código: 1005-0045",
    image: "/products/product-refil-ab3-natural.png",
    images: ["/products/product-refil-ab3-natural.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "4.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0045" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "4.000 litros" },
    ],
    features: ["Compatible amplia línea IBBL* FR600 y similares"],
  },
  {
    id: "acquabios-refil-ab3-compacto",
    name: "Refil AB3 Compacto Acquabios",
    brand: "Acquabios",
    subtitle: "Compatible IBBL* Avanti / Mio / Vivax",
    description:
      "Compatible IBBL* Avanti, Mio y Vivax. Código 1005-0064.",
    priceBefore: 0,
    priceNow: 0,
    badge: "IBBL*",
    badgeTone: "blue",
    note: "Código: 1005-0064",
    image: "/products/product-refil-ab3-compacto.png",
    images: ["/products/product-refil-ab3-compacto.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "2.500 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0064" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "2.500 litros" },
    ],
    features: ["Formato compacto", "Compatible IBBL* Avanti/Mio/Vivax"],
  },
  {
    id: "acquabios-refil-pratic-er",
    name: "Refil Pratic ER Acquabios",
    brand: "Acquabios",
    subtitle: "Codos quick-connect 1/4\"",
    description:
      "Incluye codos de conexión rápida 1/4\" para un cambio práctico. Compatible Polar WP1000/WP2000, Beliere H2O Pure, máquinas de café y otros. Código 1005-0007.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Pratic",
    badgeTone: "yellow",
    note: "Código: 1005-0007",
    image: "/products/product-refil-pratic-er.png",
    images: ["/products/product-refil-pratic-er.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "6.000 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0007" },
      { label: "Caudal", value: "60 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (≥ 5 a < 15 μm)",
      },
      { label: "Vida útil", value: "6.000 litros" },
      { label: "Conexión", value: "Codos ER 1/4\"" },
    ],
    features: [
      "Cambio rápido con codos 1/4\"",
      "Compatible Polar y máquinas de café",
    ],
  },
  {
    id: "acquabios-refil-acqua-flow",
    name: "Refil Acqua Flow Acquabios",
    brand: "Acquabios",
    subtitle: "3 etapas — bebederos de columna",
    description:
      "Filtración en 3 etapas: sólidos suspendidos, cloro, olores y mal sabor. Recomendado para bebederos de columna. Código 1005-0017.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Bebedero",
    badgeTone: "blue",
    note: "Código: 1005-0017",
    image: "/products/product-refil-acqua-flow.png",
    images: ["/products/product-refil-acqua-flow.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "40 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "1.500 L", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0017" },
      { label: "Caudal", value: "40 litros/hora" },
      {
        label: "Retención de partículas",
        value: "Clase C (≥ 5 a < 15 μm)",
      },
      { label: "Vida útil", value: "1.500 litros" },
    ],
    features: [
      "3 etapas de filtración",
      "Ideal para bebederos de columna",
    ],
  },
  {
    id: "acquabios-refil-ab40-line",
    name: "Línea Refil AB40 Acquabios",
    brand: "Acquabios",
    subtitle: "Variantes multimarca — triple filtración",
    description:
      "Línea AB40: reducción de cloro libre, retención de impurezas y triple filtración. Variantes 1005-0004 (Forusi/Viqua/Sap), 1005-0041 (Ativi/Ameris/Whilcla/Hidropol), 1005-0018 (Acqua Bella/Vitale) y 1005-0006 (New Acquabios/Herc/Ellen y más).",
    priceBefore: 0,
    priceNow: 0,
    badge: "AB40",
    badgeTone: "yellow",
    note: "Códigos: 1005-0004 · 1005-0041 · 1005-0018 · 1005-0006",
    image: "/products/product-refil-ab40-0004.png",
    images: [
      "/products/product-refil-ab40-0004.png",
      "/products/product-refil-ab40-0041.png",
      "/products/product-refil-ab40-0018.png",
      "/products/product-cartucho-ab40.png",
    ],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB40", icon: "bolt" },
      { label: "Triple", icon: "bottles" },
      { label: "Multimarca", icon: "map" },
    ],
    colors: [
      {
        name: "1005-0004",
        codes: "1005-0004",
        swatch: "#90caf9",
        image: "/products/product-refil-ab40-0004.png",
      },
      {
        name: "1005-0041",
        codes: "1005-0041",
        swatch: "#1565c0",
        image: "/products/product-refil-ab40-0041.png",
      },
      {
        name: "1005-0018",
        codes: "1005-0018",
        swatch: "#eceff1",
        image: "/products/product-refil-ab40-0018.png",
      },
      {
        name: "1005-0006",
        codes: "1005-0006",
        swatch: "#5c6bc0",
        image: "/products/product-cartucho-ab40.png",
      },
    ],
    characteristics: [
      { label: "Filtración", value: "Triple" },
      { label: "Reducción de cloro libre", value: "Sí" },
    ],
    features: [
      "Variantes para múltiples marcas",
      "Triple filtración",
      "Código 1005-0006 también disponible como cartucho AB40",
    ],
  },
  {
    id: "acquabios-refil-prf",
    name: "Línea Refil PRF Acquabios",
    brand: "Acquabios",
    subtitle: "Jarras Premium / Gold Super — modelos 06–20",
    description:
      "Repuestos PRF para modelos 06, 08, 10 y 20, Jarra Premium y Gold Super. Caja de 6 unidades. Variantes: Mineral (1005-0098), Alcalino (1005-0099), Multi capas (1005-0102 rosca / 1005-0103 troca fácil), Básico triple (1005-0101 troca fácil).",
    priceBefore: 0,
    priceNow: 0,
    badge: "PRF",
    badgeTone: "blue",
    note: "Códigos: 1005-0098 · 1005-0099 · 1005-0101 · 1005-0102 · 1005-0103",
    image: "/products/product-refil-prf-mineral.png",
    images: ["/products/product-refil-prf-mineral.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Jarra", icon: "kettle" },
      { label: "Caja x6", icon: "bottles" },
      { label: "PRF", icon: "bolt" },
    ],
    colors: [
      {
        name: "Mineral",
        codes: "1005-0098",
        swatch: "#a1887f",
        image: "/products/product-refil-prf-mineral.png",
      },
      {
        name: "Alcalino",
        codes: "1005-0099",
        swatch: "#81c784",
        image: "/products/product-refil-prf-mineral.png",
      },
      {
        name: "Multi capas",
        codes: "1005-0102 / 1005-0103",
        swatch: "#4fc3f7",
        image: "/products/product-refil-prf-mineral.png",
      },
      {
        name: "Básico triple",
        codes: "1005-0101 / 1005-0103",
        swatch: "#eeeeee",
        image: "/products/product-refil-prf-mineral.png",
      },
    ],
    characteristics: [
      { label: "Presentación", value: "Caja con 6 unidades" },
      {
        label: "Compatibilidad",
        value: "Modelos 06–20, Jarra Premium, Gold Super",
      },
    ],
    features: [
      "Mineral: Ca, Mg, K, Mn",
      "Alcalino: regula pH",
      "Acabado de cambio fácil",
    ],
  },
  {
    id: "acquabios-kit-instalacion",
    name: "Kits de instalación Acquabios",
    brand: "Acquabios",
    subtitle: "Rosca 1/2\", buchas, purificadores",
    description:
      "Kits de instalación: rosca 1/2\" (1009-0002), bucha T y soporte 1/2\" (1009-0001), kit purificadores (1009-0203), kit fijación compressor (1009-0207).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Kit",
    badgeTone: "blue",
    note: "Códigos: 1009-0002 · 1009-0001 · 1009-0203 · 1009-0207",
    image: "/products/product-accesorio-kit-instalacion.png",
    images: ["/products/product-accesorio-kit-instalacion.png"],
    tint: "blue",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Instalación", icon: "bolt" },
      { label: "1/2\"", icon: "metal" },
    ],
    characteristics: [
      { label: "Kit rosca 1/2\"", value: "1009-0002" },
      { label: "Kit bucha T + soporte", value: "1009-0001" },
      { label: "Kit purificadores", value: "1009-0203" },
      { label: "Kit fijación compressor", value: "1009-0207" },
    ],
    features: ["Todo lo necesario para instalar filtros y purificadores"],
  },
  {
    id: "acquabios-torneiras",
    name: "Torneiras / Grifos Acquabios",
    brand: "Acquabios",
    subtitle: "Metal y ABS",
    description:
      "Torneira de metal (1009-0003) y torneiras ABS (1009-0025, 1009-0026). También registro de metal 1/2\" con adaptador 1/4\" (1009-0004).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Grifo",
    badgeTone: "yellow",
    note: "Códigos: 1009-0003 · 1009-0025 · 1009-0026 · 1009-0004",
    image: "/products/product-accesorio-torneira-metal.png",
    images: [
      "/products/product-accesorio-torneira-metal.png",
      "/products/product-accesorio-torneira-abs.png",
    ],
    tint: "blue",
    category: "accesorios",
    featured: true,
    inStock: true,
    tags: [
      { label: "Metal", icon: "metal" },
      { label: "ABS", icon: "table" },
    ],
    colors: [
      {
        name: "Metal",
        codes: "1009-0003",
        swatch: "#b0bec5",
        image: "/products/product-accesorio-torneira-metal.png",
      },
      {
        name: "ABS",
        codes: "1009-0025 / 1009-0026",
        swatch: "#fafafa",
        image: "/products/product-accesorio-torneira-abs.png",
      },
    ],
    characteristics: [
      { label: "Torneira metal", value: "1009-0003" },
      { label: "Torneira ABS", value: "1009-0025 / 1009-0026" },
      { label: "Registro metal 1/2\"", value: "1009-0004" },
    ],
    features: ["Opciones metal y plástico ABS"],
  },
  {
    id: "acquabios-soportes-filtros",
    name: "Soportes y complementos Acquabios",
    brand: "Acquabios",
    subtitle: "Soportes, niple, tapones, bloqueador de aire",
    description:
      "Soporte doble plástico (1009-0163), soporte simple (1009-0162), niple 1/2\" (1009-0127), tapón 1/2\" blanco (1009-0055), tapón metalizado (1009-0050), bloqueador de aire (1009-0243). Llave para filtros 5\"/7\"/9 3/4\" ya registrada como 1009-0019.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Accesorio",
    badgeTone: "blue",
    note: "Códigos: 1009-0163 · 1009-0162 · 1009-0127 · 1009-0055 · 1009-0050 · 1009-0243",
    image: "/products/product-accesorio-suporte-duplo.png",
    images: ["/products/product-accesorio-suporte-duplo.png"],
    tint: "blue",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Soporte", icon: "metal" },
      { label: "Montaje", icon: "bolt" },
    ],
    characteristics: [
      { label: "Soporte doble", value: "1009-0163" },
      { label: "Soporte simple", value: "1009-0162" },
      { label: "Niple 1/2\"", value: "1009-0127" },
      { label: "Tapón blanco 1/2\"", value: "1009-0055" },
      { label: "Tapón metalizado 1/2\"", value: "1009-0050" },
      { label: "Bloqueador de aire", value: "1009-0243" },
    ],
    features: ["Complementos de montaje e instalación"],
  },
  {
    id: "acquabios-mangueiras",
    name: "Mangueras Acquabios",
    brand: "Acquabios",
    subtitle: "1/4\", 5/16\", 3/8\" y corrugada",
    description:
      "Mangueras: 2 m 1/4\" (1009-0218), 5 m 1/4\" (1009-0248), 1,2 m 5/16\" (1009-0021), 5 m 5/16\" (1009-0246), 5 m 3/8\" (1009-0244), corrugada gris 8,5×13 mm rollo 50 m (1009-0228).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Manguera",
    badgeTone: "yellow",
    note: "Códigos: 1009-0218 · 1009-0248 · 1009-0021 · 1009-0246 · 1009-0244 · 1009-0228",
    image: "/products/product-accesorio-kit-instalacion.png",
    images: ["/products/product-accesorio-kit-instalacion.png"],
    tint: "blue",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "1/4\"", icon: "metal" },
      { label: "3/8\"", icon: "metal" },
    ],
    characteristics: [
      { label: "2 m 1/4\"", value: "1009-0218" },
      { label: "5 m 1/4\"", value: "1009-0248" },
      { label: "1,2 m 5/16\"", value: "1009-0021" },
      { label: "5 m 5/16\"", value: "1009-0246" },
      { label: "5 m 3/8\"", value: "1009-0244" },
      { label: "Corrugada 50 m", value: "1009-0228" },
    ],
    features: ["Varias medidas y largos para instalación"],
  },
  {
    id: "acquabios-conectores-er",
    name: "Conectores y válvulas ER Acquabios",
    brand: "Acquabios",
    subtitle: "Push-fit, codos, válvulas y reductores",
    description:
      "Línea completa de adaptadores ER rectos/T/Y, codos, conectores con contratuerca, válvulas ER, válvula de reducción de presión y válvula tank. Medidas 1/4\" y 3/8\" con roscas 1/4\" y 1/2\". Códigos 1009-0139 a 1009-0247 (familia ER).",
    priceBefore: 0,
    priceNow: 0,
    badge: "ER",
    badgeTone: "blue",
    note: "Familia 1009-01xx / 1009-02xx — ver características",
    image: "/products/product-accesorio-conectores-er.png",
    images: ["/products/product-accesorio-conectores-er.png"],
    tint: "blue",
    category: "accesorios",
    featured: true,
    inStock: true,
    tags: [
      { label: "Push-fit", icon: "bolt" },
      { label: "1/4\"", icon: "metal" },
      { label: "3/8\"", icon: "metal" },
    ],
    characteristics: [
      { label: "Adaptador ER recto RI 1/2\"", value: "1009-0147 / 1009-0175" },
      {
        label: "Adaptador ER hembra 1/2\"",
        value: "1009-0183 / 1009-0247",
      },
      { label: "Adaptador T ER 3X", value: "1009-0145 / 1009-0174" },
      { label: "T ER con RI 1/4\"", value: "1009-0146" },
      { label: "Conector recto ER", value: "1009-0223 / 1009-0176" },
      { label: "Conector con contratuerca", value: "1009-0182" },
      { label: "Conector rosca 1/2\" + válvula", value: "1009-0084" },
      { label: "Conector mangueira 7,5", value: "1009-0126" },
      { label: "Conector Y ER", value: "1009-0142" },
      { label: "Codo entrada / salida", value: "1009-0052 / 1009-0053" },
      { label: "Codos ER", value: "1009-0139 … 1009-0173" },
      { label: "Válvulas ER", value: "1009-0143 / 1009-0144 / 1009-0179 / 1009-0186" },
      { label: "Reducción de presión", value: "1009-0216" },
      { label: "Válvula Tank", value: "1009-0180" },
    ],
    features: [
      "Conexión rápida push-fit",
      "Amplia gama de codos y válvulas",
      "Medidas 1/4\" y 3/8\"",
    ],
  },
];
