import type { ProductOffer } from "@/types/product";
import { PRODUCT_CATEGORIES } from "@/types/product";
import { acquabiosExtraProducts } from "@/lib/catalog-acquabios-extra";

/**
 * Catálogo importado desde WooCommerce (solo datos útiles).
 * El CSV no traía precios, imágenes ni categorías.
 * Categorías inferidas por nombre; precio "Consultar" hasta completar.
 */
export const catalogProducts: ProductOffer[] = [
  {
    id: "wc-323",
    name: "Dispensador Básico + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-324",
    name: "Dispensador Básico + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-325",
    name: "Dispensador Básico + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-326",
    name: "Dispensador Básico + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-327",
    name: "Bomba Eléctrica USB + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-328",
    name: "Bomba Eléctrica USB + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-329",
    name: "Bomba Eléctrica USB + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-330",
    name: "Bomba Eléctrica USB + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-332",
    name: "Recarga de 20 lt",
    priceBefore: 2500,
    priceNow: 2500,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-333",
    name: "Envase + Recarga de 20 lt",
    priceBefore: 5800,
    priceNow: 5000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-334",
    name: "5 Recargas de 20 lt c/u",
    priceBefore: 14000,
    priceNow: 12500,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-337",
    name: "Bomba Electrónica USB",
    priceBefore: 7000,
    priceNow: 2700,
    badge: "-61%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "bombas",
    inStock: true,
    tags: [
      { label: "USB", icon: "bolt" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-338",
    name: "Dispensador Básico",
    priceBefore: 7000,
    priceNow: 5000,
    badge: "-29%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-848",
    name: "Dispensador con filtro de sistema osmosis inversa",
    description: "Dispensador de agua sistema OSMOSIS INVERSA, no ocupa bidones ya que purifica y filtra el agua potable, conectado directo a una llave de red potable. Dispensa agua en 3 temperat…",
    priceBefore: 320000,
    priceNow: 297500,
    badge: "-7%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-851",
    name: "Filtro sistema osmosis inversa",
    description: "Filtro de osmosis inversa Agua Ser purificada. Mejora la calidad y sabor del agua de tu casa, filtro se instala debajo del lavaplatos. Elimina el 90% de las partículas, sustanci…",
    priceBefore: 120000,
    priceNow: 95000,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-960",
    name: "Recarga PACK 12unidades de agua gasificada 500cc",
    description: "Pack 12 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-997",
    name: "Recarga PACK 6unidades agua gasificada 1.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4200,
    priceNow: 4200,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-999",
    name: "Recarga PACK 6unidades de agua gasificada 2.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1001",
    name: "Recarga PACK 6unidades de agua gasificada 3lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 6000,
    priceNow: 6000,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1003",
    name: "Compresor para dispensador",
    priceBefore: 56000,
    priceNow: 55000,
    badge: "-2%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1541",
    name: "Soporte para Bidones",
    description: "Reemplazo universal para dispensadores de agua frío/calor 17 cm diametro. ($9.990 c/u) ENVIOS NO INCLUIDO, SE CALCULA DEPENDIENDO COMUNA",
    priceBefore: 15990,
    priceNow: 9990,
    badge: "-38%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1546",
    name: "Racks para 5 Bidones de 20 lts",
    description: "Capacidad para 5 bidones",
    priceBefore: 54000,
    priceNow: 40000,
    badge: "-26%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1549",
    name: "Llaves de repuesto para dispensadores frío/calor de pedestal",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1553",
    name: "Llaves de repuesto para dispensadores frío/calor de sobremesa",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1564",
    name: "Bidón completo de 10 lts",
    priceBefore: 3900,
    priceNow: 3900,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1569",
    name: "Recarga bidón de 10 lts",
    priceBefore: 2200,
    priceNow: 1800,
    badge: "-18%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1571",
    name: "Dispensador de Sobremesa para agua fría y caliente",
    description: "Grados de la máquina: Agua caliente 85°c-95°c Agua fría 10°c-15°c",
    priceBefore: 50000,
    priceNow: 39000,
    badge: "-22%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-1590",
    name: "Dispensador de Pedestal 2 llaves con sistema compresor",
    priceBefore: 137000,
    priceNow: 137000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1930",
    name: "Dispensador Pedestal 3 Llaves Con Sistema Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 143000,
    priceNow: 143000,
    badge: "Destacado",
    badgeTone: "yellow",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    featured: true,
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1937",
    name: "Rack Para 3 Bidones 20l",
    priceBefore: 35000,
    priceNow: 30000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1941",
    name: "Rack Para 2 Bidones 20l",
    priceBefore: 20000,
    priceNow: 20000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1944",
    name: "Tapas Para Bidones De 20l Y 10l",
    priceBefore: 100,
    priceNow: 72,
    badge: "-28%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1947",
    name: "Manilla Sujetadora De Bidones",
    priceBefore: 2000,
    priceNow: 1500,
    badge: "-25%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1981",
    name: "Hielo 1 kg",
    description: "Hielo de agua purificada 1 kilo SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 800,
    priceNow: 600,
    badge: "-25%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1984",
    name: "Hielo 2 kg",
    description: "Hielo de agua purificada 2 kilos SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1987",
    name: "Rack Para 3 Bidones 20 Litros",
    description: "RACK SOPORTE PARA 3 BIDONES 20 LITROS",
    priceBefore: 30000,
    priceNow: 18000,
    badge: "-40%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2341",
    name: "Dispensador Sobremesa Agua Fría Y Caliente",
    description: "DISPENSADOR ELECTRICO DE SOBREMESA, CON SISTEMA VENTILADOR, AGUA FRIA ENTRE 10 Y 15 GRADOS Y AGUA CALIENTE ENTRE 85 Y 90 GRADOS °C.",
    priceBefore: 50000,
    priceNow: 45000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-2346",
    name: "Dispensador Digital de Té Incluye Tetera Y Hervidor",
    description: "DISPENSADOR DIGITAL AUTOMATICO DE TE INCLUYE ACCESORIOS TETERA Y HERVIDOR COMPARTIMIENTO INFERIOR PARA BIDON DE 20 LITROS",
    priceBefore: 100000,
    priceNow: 80000,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/product-tea-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2354",
    name: "Bidón Desechable 6 Litros",
    description: "BIDON DESECHABLE 6 LITROS",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "6 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2444",
    name: "Dispensador Pedestal 3 Llaves Con Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 170000,
    priceNow: 154700,
    badge: "-9%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-2447",
    name: "Dispensador Pedestal 2 Llaves Con Frigobar",
    description: "Dispensador pedestal 2 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 90°c. Con motor compresor. Compartimiento enfría tus bebidas.",
    priceBefore: 150000,
    priceNow: 130900,
    badge: "-13%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2579",
    name: "Servicio Instalación Dispensador Ósmosis",
    description: "Contamos con servicio de instalación a domicilio (solo para Santiago, RM) para dispensador osmosis. Para mayor información por favor comunicarse al +56944786330",
    priceBefore: 40000,
    priceNow: 35700,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "servicios",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
      { label: "Santiago RM", icon: "map" },
    ],
  },
  {
    id: "acquabios-ultra-ice",
    name: "ULTRA ICE Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador UVC-LED — agua fría y ambiente · refil alcalino",
    description:
      "Compacto y altamente eficiente, con nicho iluminado por tecnología UVC-LED que elimina el 99,9% de bacterias. Depósito antibacteriano ultra-resistente, refrigeración por compresor y refil alcalino. Ideal para hogar u oficina: agua natural y fría en un solo equipo. Medidas 40 × 26 × 35 cm.",
    priceBefore: 0,
    priceNow: 0,
    badge: "UVC-LED",
    badgeTone: "green",
    note: "Códigos: Blanco 1008-0179/0180 · Negro 1008-0181/0182 · Plata 1008-0183/0184",
    image: "/products/product-ultra-ice-plata.png",
    images: [
      "/products/product-ultra-ice-plata.png",
      "/products/product-ultra-ice-blanco.png",
      "/products/product-ultra-ice-negro.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "UVC-LED", icon: "bolt" },
      { label: "Agua fría", icon: "snowflake" },
      { label: "Alcalina", icon: "kettle" },
    ],
    characteristics: [
      { label: "Tecnología", value: "UVC-LED (elimina 99,9% de bacterias)" },
      { label: "Refil", value: "Alcalino · ultra duradero" },
      { label: "Flujo del agua", value: "60 litros por hora" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      { label: "Retención de partículas", value: "de >0,5 a <1 μm" },
      {
        label: "Vida útil del cartucho",
        value: "2.500 litros o 6 meses",
      },
      {
        label: "Capacidad de refrigeración",
        value: "2,2 litros por hora",
      },
      {
        label: "Volumen interno del reservorio",
        value: "2,3 litros",
      },
      { label: "Medidas (Al × An × Pr)", value: "40 × 26 × 35 cm" },
    ],
    features: [
      "Tecnología UVC-LED con nicho iluminado",
      "Refil alcalino",
      "Sistema de refrigeración por compresor",
      "Cartucho de fácil sustitución: gira y cambia",
      "LED indicativo para el reemplazo del cartucho",
      "Reservorio antibacterial y ultra resistente",
      "Bajo consumo de energía",
      "Calidad comprobada",
    ],
    specs: [
      { label: "Voltaje (V)", value: "220V / 110V" },
      { label: "Potencia (W)", value: "80W / 100W" },
      { label: "Frecuencia (Hz)", value: "50–60 Hz / 60 Hz" },
    ],
    colors: [
      {
        name: "Plata",
        codes: "1008-0183 (220V) / 1008-0184 (127V)",
        swatch: "#c5ccd3",
        image: "/products/product-ultra-ice-plata.png",
      },
      {
        name: "Blanco",
        codes: "1008-0179 (220V) / 1008-0180 (127V)",
        swatch: "#f4f6f8",
        image: "/products/product-ultra-ice-blanco.png",
      },
      {
        name: "Negro",
        codes: "1008-0181 (220V) / 1008-0182 (127V)",
        swatch: "#1a1a1a",
        image: "/products/product-ultra-ice-negro.png",
      },
    ],
  },
  {
    id: "acquabios-easy",
    name: "EASY Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador de agua natural",
    description:
      "Los colores sólidos fueron diseñados para combinar con las líneas de electrodomésticos, de esta forma el depurador se integra en la decoración. Purificador de mesa con sistema de intercambio fácil de cartucho y agua pura con un clic. Certificación INMETRO de desempeño en reducción de cloro y retención de partículas.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1008-0013 (Negro)",
    image: "/products/product-easy-negro.png",
    images: [
      "/products/product-easy-negro.png",
      "/products/product-easy-rojo.png",
      "/products/product-easy-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Agua natural", icon: "bottles" },
      { label: "Sobremesa", icon: "table" },
      { label: "Fácil recambio", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo del agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "de ≥5 a <15 μm",
      },
      {
        label: "Vida útil del cartucho",
        value: "1.500 litros o 6 meses",
      },
      { label: "Instalación", value: "Mesa (sobremesa)" },
    ],
    features: [
      "Sistema de intercambio fácil (Easy Replacement System)",
      "Agua pura con un clic (Pure Water One Click)",
      "Diseño para combinar con electrodomésticos",
      "Cartucho de fácil sustitución",
      "Certificación INMETRO de desempeño",
      "Instalación en mesa, compacto y discreto",
    ],
    colors: [
      {
        name: "Negro",
        codes: "1008-0013",
        swatch: "#1a1a1a",
        image: "/products/product-easy-negro.png",
      },
      {
        name: "Rojo",
        codes: "1008-0014",
        swatch: "#c62828",
        image: "/products/product-easy-rojo.png",
      },
      {
        name: "Blanco",
        codes: "1008-0012",
        swatch: "#f4f6f8",
        image: "/products/product-easy-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-easy-special",
    name: "EASY Special Edition Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador de agua natural — edición especial",
    description:
      "Desarrollado siguiendo las tendencias globales en diseño y acabados, asegurando belleza y ambientes contemporáneos. Misma tecnología del EASY con acabados metálicos premium. Incluye llave de reemplazo de cartucho y válvula de instalación compatible con tubería de 1/2\" y salida de manguera de 1/4\".",
    priceBefore: 0,
    priceNow: 0,
    badge: "Edición especial",
    badgeTone: "yellow",
    note: "Código principal: 1008-0015 (Rose Gold)",
    image: "/products/product-easy-special-rosegold.png",
    images: [
      "/products/product-easy-special-rosegold.png",
      "/products/product-easy-special-gris.png",
    ],
    tint: "yellow",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Agua natural", icon: "bottles" },
      { label: "Edición especial", icon: "metal" },
      { label: "Sobremesa", icon: "table" },
    ],
    characteristics: [
      { label: "Flujo del agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "de ≥5 a <15 μm",
      },
      {
        label: "Vida útil del cartucho",
        value: "1.500 litros o 6 meses",
      },
      { label: "Instalación", value: "Mesa (sobremesa)" },
    ],
    features: [
      "Acabados metálicos premium (tendencia global)",
      "Sistema de intercambio fácil de cartucho",
      "Agua pura con un clic",
      "Incluye llave de reemplazo",
      "Incluye válvula de instalación 1/2\" → 1/4\"",
      "Certificación INMETRO de desempeño",
    ],
    colors: [
      {
        name: "Rose Gold",
        codes: "1008-0015",
        swatch: "#b76e79",
        image: "/products/product-easy-special-rosegold.png",
      },
      {
        name: "Gris",
        codes: "1008-0026",
        swatch: "#6b7280",
        image: "/products/product-easy-special-gris.png",
      },
    ],
  },
  {
    id: "acquabios-easy-cartucho",
    name: "Cartucho de reposición EASY Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho de filtración para línea EASY",
    description:
      "Cartucho de reposición oficial para purificadores Acquabios EASY y EASY Special Edition. Mantiene el flujo, la reducción de cloro/olor/mal sabor y la retención de partículas del equipo. Código 1005-0047.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Consumible",
    badgeTone: "blue",
    note: "Código: 1005-0047",
    image: "/products/product-easy-cartucho.png",
    images: ["/products/product-easy-cartucho.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "Repuesto", icon: "bolt" },
      { label: "1.500 litros", icon: "bottles" },
    ],
    characteristics: [
      { label: "Flujo", value: "40 L/h" },
      { label: "Vida útil", value: "1.500 litros o 6 meses" },
      {
        label: "Compatibilidad",
        value: "EASY y EASY Special Edition",
      },
      { label: "Código", value: "1005-0047" },
    ],
    features: [
      "Repuesto oficial Acquabios",
      "Compatible con EASY y Special Edition",
      "Fácil sustitución en el equipo",
      "Mantiene el desempeño de filtración",
    ],
  },
  {
    id: "acquabios-premium-grifo",
    name: "Premium Filtro con Grifo Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo integrado",
    description:
      "Tu cocina merece la Premium. Filtro con grifo de pared Acquabios: reduce cloro, olor y mal sabor, con volantes ergonómicos de apertura fácil (1/4 de vuelta). Diseño compacto para instalar en muro. Certificación INMETRO de desempeño. Envase tipo blister para gancho; caja con 4 unidades.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0022 (Negro / Rose Gold)",
    image: "/products/product-premium-negro-rosegold.png",
    images: [
      "/products/product-premium-negro-rosegold.png",
      "/products/product-premium-blanco-rosegold.png",
      "/products/product-premium-negro-cromo.png",
      "/products/product-premium-rojo-rosegold.png",
      "/products/product-premium-blanco-azul.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Apertura fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      {
        label: "Apertura",
        value: "Fácil, 1/4 de vuelta",
      },
    ],
    features: [
      "Filtro con grifo integrado",
      "Abre fácil: 1/4 de vuelta",
      "Volantes ergonómicos, eficientes y durables",
      "Instalación de pared",
      "Reducción de cloro, olor y mal sabor",
      "Certificación INMETRO de desempeño",
    ],
    colors: [
      {
        name: "Negro / Rose Gold",
        codes: "1006-0022",
        swatch: "#1a1a1a",
        image: "/products/product-premium-negro-rosegold.png",
      },
      {
        name: "Blanco / Rose Gold",
        codes: "1006-0023",
        swatch: "#f4f6f8",
        image: "/products/product-premium-blanco-rosegold.png",
      },
      {
        name: "Negro / Cromo",
        codes: "1019-0003",
        swatch: "#2a2a2a",
        image: "/products/product-premium-negro-cromo.png",
      },
      {
        name: "Rojo / Rose Gold",
        codes: "1006-0072",
        swatch: "#c62828",
        image: "/products/product-premium-rojo-rosegold.png",
      },
      {
        name: "Blanco / Azul",
        codes: "1006-0024",
        swatch: "#2f6fed",
        image: "/products/product-premium-blanco-azul.png",
      },
    ],
  },
  {
    id: "acquabios-filtro-mesa",
    name: "Filtro con Grifo de Mesa Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de mesa con grifo — abre fácil",
    description:
      "Filtro con grifo de mesa Acquabios: reduce cloro, olor y mal sabor, con apertura fácil y diseño compacto para instalar sobre el mesón. Flujo de 40 L/h y cartucho de larga duración. Certificación INMETRO de desempeño y sello de calidad y tecnología.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0145 (Cromo)",
    image: "/products/product-filtro-mesa-cromo.png",
    images: [
      "/products/product-filtro-mesa-cromo.png",
      "/products/product-filtro-mesa-negro.png",
      "/products/product-filtro-mesa-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De mesa", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Abre fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "Mesa (sobremesa)" },
      { label: "Apertura", value: "Abre fácil" },
    ],
    features: [
      "Filtro con grifo de mesa",
      "Sistema abre fácil",
      "Reducción de cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho AB40",
    ],
    colors: [
      {
        name: "Cromo",
        codes: "1006-0145",
        swatch: "#c0c5cc",
        image: "/products/product-filtro-mesa-cromo.png",
      },
      {
        name: "Negro",
        codes: "1006-0144",
        swatch: "#1a1a1a",
        image: "/products/product-filtro-mesa-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0143",
        swatch: "#f4f6f8",
        image: "/products/product-filtro-mesa-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-filtro-pared",
    name: "Filtro con Grifo de Pared Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo — abre fácil",
    description:
      "Filtro con grifo de pared Acquabios: misma tecnología de filtración en formato mural. Reduce cloro, olor y mal sabor, con apertura fácil. Ideal cuando prefieres instalación en muro. Certificación INMETRO de desempeño.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0141 (Cromo)",
    image: "/products/product-filtro-pared-cromo.png",
    images: [
      "/products/product-filtro-pared-cromo.png",
      "/products/product-filtro-pared-negro.png",
      "/products/product-filtro-pared-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Abre fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      { label: "Apertura", value: "Abre fácil" },
    ],
    features: [
      "Filtro con grifo de pared",
      "Sistema abre fácil",
      "Reducción de cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho AB40",
    ],
    colors: [
      {
        name: "Cromo",
        codes: "1006-0141",
        swatch: "#c0c5cc",
        image: "/products/product-filtro-pared-cromo.png",
      },
      {
        name: "Negro",
        codes: "1006-0140",
        swatch: "#1a1a1a",
        image: "/products/product-filtro-pared-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0139",
        swatch: "#f4f6f8",
        image: "/products/product-filtro-pared-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-cartucho-ab40",
    name: "Cartucho de reposición AB40 Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho AB40 — triple filtración",
    description:
      "Cartucho de reposición Acquabios AB40 para filtros con grifo de mesa y de pared. Triple filtración, alta eficiencia en retención de partículas y reducción de cloro, olor y mal sabor. Viene con un cartucho adicional gratis. Código 1005-0006.",
    priceBefore: 0,
    priceNow: 0,
    badge: "2x1",
    badgeTone: "yellow",
    note: "Código: 1005-0006 · Incluye cartucho adicional gratis",
    image: "/products/product-cartucho-ab40.png",
    images: ["/products/product-cartucho-ab40.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB40", icon: "bolt" },
      { label: "Triple filtración", icon: "bottles" },
      { label: "1.500 litros", icon: "bottles" },
    ],
    characteristics: [
      { label: "Modelo", value: "AB40" },
      { label: "Código", value: "1005-0006" },
      { label: "Filtración", value: "Triple" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Alta eficiencia",
      },
      {
        label: "Compatibilidad",
        value: "Filtro grifo de mesa y de pared",
      },
    ],
    features: [
      "Triple filtración",
      "Alta eficiencia en retención de partículas",
      "Reduce cloro, olor y mal sabor",
      "Incluye un cartucho adicional gratis",
      "Repuesto oficial Acquabios AB40",
    ],
  },
  {
    id: "acquabios-colors",
    name: "COLORS Filtro con Grifo de Pared Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo — ¡un toque de color y todo cambia!",
    description:
      "Línea COLORS de Acquabios: filtro con grifo de pared en colores vibrantes. Sistema de recambio fácil sin herramientas, reduce cloro, olor y mal sabor, y retiene partículas clase D. Ideal para dar un toque de color a la cocina. Envase blister para gancho; caja con 6 unidades. Certificación INMETRO y sello de calidad y tecnología.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0092 (Negro)",
    image: "/products/product-colors-negro.png",
    images: [
      "/products/product-colors-negro.png",
      "/products/product-colors-blanco.png",
      "/products/product-colors-azul.png",
      "/products/product-colors-rojo.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Colores", icon: "metal" },
      { label: "Recambio fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      {
        label: "Recambio",
        value: "Sistema fácil, sin herramientas",
      },
    ],
    features: [
      "Un toque de color y todo cambia",
      "Sistema de intercambio fácil de cartucho",
      "Filtro con grifo de pared integrado",
      "Reducción de cloro, olor y mal sabor",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho COLORS",
    ],
    colors: [
      {
        name: "Negro",
        codes: "1006-0092",
        swatch: "#1a1a1a",
        image: "/products/product-colors-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0001",
        swatch: "#f4f6f8",
        image: "/products/product-colors-blanco.png",
      },
      {
        name: "Azul",
        codes: "1006-0002",
        swatch: "#1e6fd9",
        image: "/products/product-colors-azul.png",
      },
      {
        name: "Rojo",
        codes: "1006-0003",
        swatch: "#c62828",
        image: "/products/product-colors-rojo.png",
      },
    ],
  },
  {
    id: "acquabios-colors-cartucho",
    name: "Cartucho de reposición COLORS Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho para línea COLORS",
    description:
      "Cartucho de reposición oficial para filtros COLORS Acquabios. Flujo 40 L/h, vida útil 1.500 litros y retención de partículas clase D. Un cartucho equivale a aproximadamente 75 galones de agua (cerca de 20 bidones de 20 L). Código 1007-0001. También disponibles carcasas de reposición en rojo (1007-0003) y negro (1007-0004).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Consumible",
    badgeTone: "blue",
    note: "Código: 1007-0001 · Carcasas: 1007-0003 (rojo) / 1007-0004 (negro)",
    image: "/products/product-colors-cartucho.png",
    images: ["/products/product-colors-cartucho.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "COLORS", icon: "bolt" },
      { label: "1.500 litros", icon: "bottles" },
      { label: "Repuesto", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código cartucho", value: "1007-0001" },
      { label: "Flujo", value: "40 L/h" },
      { label: "Vida útil", value: "1.500 litros" },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      {
        label: "Equivalencia",
        value: "≈ 75 galones / ~20 bidones de 20 L",
      },
      {
        label: "Compatibilidad",
        value: "Línea COLORS Acquabios",
      },
    ],
    features: [
      "Repuesto oficial línea COLORS",
      "Recambio fácil en el equipo",
      "Reduce cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Carcasas opcionales rojo y negro",
    ],
  },
  {
    id: "acquabios-grifo-bano",
    name: "Grifo de Mesa para Baño Acquabios",
    brand: "Acquabios",
    subtitle: "Grifería para lavamanos — abre fácil 1/4 de vuelta",
    description:
      "Los baños también siguen las tendencias. Grifo de mesa para baño Acquabios con cuello de cisne elegante, llave de cuatro asas (cuadriseta) y apertura fácil de 1/4 de vuelta. Ideal para lavamanos tipo vessel o vanitory. Acabados en tendencia para un baño más elegante.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1020-0012 (Rojo)",
    image: "/products/product-grifo-bano-rojo.png",
    images: [
      "/products/product-grifo-bano-rojo.png",
      "/products/product-grifo-bano-cromo.png",
      "/products/product-grifo-bano-blanco.png",
      "/products/product-grifo-bano-gris.png",
      "/products/product-grifo-bano-negro.png",
    ],
    tint: "blue",
    category: "accesorios",
    featured: true,
    inStock: true,
    tags: [
      { label: "Para baño", icon: "table" },
      { label: "Abre fácil", icon: "bolt" },
      { label: "Cuello de cisne", icon: "metal" },
    ],
    characteristics: [
      { label: "Tipo", value: "Grifo de mesa para baño" },
      { label: "Instalación", value: "Sobre mesón / lavamanos" },
      {
        label: "Apertura",
        value: "Fácil, 1/4 de vuelta",
      },
      {
        label: "Llave",
        value: "Cuatro asas (cuadriseta)",
      },
      {
        label: "Diseño",
        value: "Cuello de cisne alto",
      },
    ],
    features: [
      "Abre fácil: 1/4 de vuelta",
      "Llave cuatro asas (cuadriseta)",
      "Diseño elegante cuello de cisne",
      "Ideal para lavamanos y vanitory",
      "Variedad de colores en tendencia",
      "Base y manilla en cromo pulido",
    ],
    colors: [
      {
        name: "Blanco",
        codes: "1020-0008",
        swatch: "#f4f6f8",
        image: "/products/product-grifo-bano-blanco.png",
      },
      {
        name: "Gris",
        codes: "1020-0009",
        swatch: "#9aa3ad",
        image: "/products/product-grifo-bano-gris.png",
      },
      {
        name: "Cromo",
        codes: "1020-0010",
        swatch: "#c0c5cc",
        image: "/products/product-grifo-bano-cromo.png",
      },
      {
        name: "Negro",
        codes: "1020-0011",
        swatch: "#1a1a1a",
        image: "/products/product-grifo-bano-negro.png",
      },
      {
        name: "Rojo",
        codes: "1020-0012",
        swatch: "#c62828",
        image: "/products/product-grifo-bano-rojo.png",
      },
    ],
  },
  {
    id: "acquabios-acqua-blue",
    name: "ACQUA BLUE Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de agua para punto de entrada (POE)",
    description:
      "Protección para tu casa. Filtro Acqua Blue Acquabios para punto de entrada: retiene partículas, reduce cloro y aporta eficiencia bacteriológica en la red de agua de tu hogar. Incluye el primer cartucho de reposición gratis. Rosca 3/4\", compatible con cartucho push-in o roscado 1/2\". Tapa de alta resistencia con soporte de fijación integrado e insertos metálicos en las conexiones. Certificación INMETRO.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Cartucho gratis",
    badgeTone: "yellow",
    note: "Código: 1000-0065 · Incluye primer cartucho de reposición gratis",
    image: "/products/product-acqua-blue.png",
    images: [
      "/products/product-acqua-blue.png",
      "/products/product-acqua-blue-caja.png",
      "/products/product-acqua-blue-cartucho.png",
      "/products/product-acqua-blue-llave.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Punto de entrada", icon: "bolt" },
      { label: "1200 L/h", icon: "bottles" },
      { label: "3/4\"", icon: "metal" },
    ],
    characteristics: [
      { label: "Código", value: "1000-0065" },
      { label: "Presión de operación", value: "19,6 a 588 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca", value: "3/4\"" },
      {
        label: "Compatibilidad cartucho",
        value: "Push-in o roscado 1/2\"",
      },
      {
        label: "Clase de retención de partículas",
        value: "Clase D (≥ 15 a < 30 μm)",
      },
      { label: "Tamaño", value: "9 3/4\"" },
      { label: "Flujo / caudal", value: "1.200 litros por hora" },
      { label: "Color", value: "Azul (cuerpo) / Negro (tapa)" },
    ],
    features: [
      "Protección para toda la casa (punto de entrada / POE)",
      "Soporte de fijación a la pared integrado en la tapa",
      "Tapa de alta resistencia a la intemperie",
      "Insertos metálicos en las conexiones",
      "Incluye primer cartucho de reposición gratis",
      "Reducción de cloro, retención de partículas y eficiencia bacteriológica",
      "Certificación INMETRO",
    ],
  },
  {
    id: "acquabios-acqua-blue-llave",
    name: "Llave para filtros 5\", 7\" y 9 3/4\"",
    brand: "Acquabios",
    subtitle: "Chave de abertura — código 1009-0019",
    description:
      "Llave de mantenimiento Acquabios (1009-0019) para apertura y cierre de carcasas de filtros 5\", 7\" y 9 3/4\" (incluye Acqua Blue, Acqua 5/200/230 y similares). Facilita el cambio de cartucho y ayuda a evitar fugas por sellado incorrecto.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Accesorio",
    badgeTone: "blue",
    note: "Código: 1009-0019 · Filtros 5\" / 7\" / 9 3/4\"",
    image: "/products/product-acqua-blue-llave.png",
    images: ["/products/product-acqua-blue-llave.png"],
    tint: "blue",
    category: "accesorios",
    featured: false,
    inStock: true,
    tags: [
      { label: "Mantenimiento", icon: "bolt" },
      { label: "5\"–9 3/4\"", icon: "metal" },
    ],
    characteristics: [
      { label: "Código", value: "1009-0019" },
      { label: "Color", value: "Negro" },
      {
        label: "Compatibilidad",
        value: "Filtros 5\", 7\" y 9 3/4\"",
      },
      { label: "Material", value: "Plástico de alta resistencia" },
    ],
    features: [
      "Facilita el mantenimiento y el cambio de cartucho",
      "Ayuda a prevenir fugas por sellado incorrecto",
      "Compatible con línea Acqua y Acqua Blue",
    ],
  },
  {
    id: "acquabios-troca-facil",
    name: "Filtro Troca Fácil Acquabios",
    brand: "Acquabios",
    subtitle: "Línea Acqua — filtro de cambio rápido (girou trocou)",
    description:
      "Un solo producto, múltiples usos. Filtro Troca Fácil Acquabios con sistema de mantenimiento rápido: giras y cambias el cartucho. Ideal para máquinas de café, jugos, hielo o instalación bajo la pileta. Agua alcalina con protección bacteriológica Ultra Clase A, reducción de cloro libre, válvula de bloqueo (solo libera agua si está completamente encajado), trava de seguridad y soporte articulado.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Cambio fácil",
    badgeTone: "blue",
    note: "Código: 1000-0089 (Clase A) · Opción 1000-0090 (Clase C)",
    image: "/products/product-troca-facil.png",
    images: [
      "/products/product-troca-facil.png",
      "/products/product-troca-facil-contexto.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "100 L/h", icon: "bottles" },
      { label: "Clase A", icon: "bolt" },
      { label: "Bajo pileta", icon: "table" },
    ],
    colors: [
      {
        name: "Blanco",
        codes: "1000-0089 / 1000-0090",
        swatch: "#f5f5f5",
        image: "/products/product-troca-facil.png",
      },
    ],
    characteristics: [
      { label: "Código Clase A", value: "1000-0089" },
      { label: "Código opción Clase C", value: "1000-0090" },
      { label: "Caudal nominal", value: "100 L/h" },
      {
        label: "Clase de retención de partículas",
        value: "Clase A (≥ 0,5 a < 1 μm)",
      },
      { label: "Vida útil", value: "3.000 litros o 6 meses" },
      { label: "Reducción de cloro libre", value: "Aplicável" },
      { label: "Color", value: "Blanco" },
      { label: "Línea", value: "Acqua" },
    ],
    features: [
      "Sistema girou trocou — cambio rápido de cartucho",
      "pH alcalino y protección bacteriológica Ultra Clase A",
      "Válvula de bloqueo de seguridad",
      "Trava de seguridad y soporte articulado",
      "Ideal para café, jugos, hielo o pileta",
      "Instalación bajo mesón / bajo pileta",
    ],
  },
  {
    id: "acquabios-troca-facil-cartucho",
    name: "Cartucho Troca Fácil Acquabios",
    brand: "Acquabios",
    subtitle: "Refil de reposición — doble O-ring",
    description:
      "Cartucho (refil) de reposición para el Filtro Troca Fácil Acquabios. Corazón de la purificación: agua alcalina, retención Clase A y doble O-ring de ultra sellado. Capacidad de hasta 3.000 litros. Se recomienda cambiar cada 6 meses o cuando disminuya el caudal. Códigos 1005-0146 (Clase A) y 1005-0159 (opción Clase C).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1005-0146 (Clase A) · Opción 1005-0159 (Clase C)",
    image: "/products/product-troca-facil-cartucho.png",
    images: [
      "/products/product-troca-facil-cartucho.png",
      "/products/product-troca-facil-cartucho-contexto.png",
    ],
    tint: "blue",
    category: "consumibles",
    featured: false,
    inStock: true,
    tags: [
      { label: "Repuesto", icon: "bolt" },
      { label: "3.000 L", icon: "bottles" },
      { label: "Doble O-ring", icon: "metal" },
    ],
    colors: [
      {
        name: "Blanco",
        codes: "1005-0146 / 1005-0159",
        swatch: "#f5f5f5",
        image: "/products/product-troca-facil-cartucho.png",
      },
    ],
    characteristics: [
      { label: "Código Clase A", value: "1005-0146" },
      { label: "Código opción Clase C", value: "1005-0159" },
      { label: "Capacidad", value: "Hasta 3.000 litros" },
      { label: "Sellado", value: "Doble O-ring (ultra sellado)" },
      {
        label: "Compatibilidad",
        value: "Filtro Troca Fácil (1000-0089 / 1000-0090)",
      },
      {
        label: "Mantenimiento",
        value: "Cada 6 meses o ante baja de caudal",
      },
    ],
    features: [
      "Bacteriológico Ultra Clase A",
      "pH alcalino",
      "Doble O-ring de ultra sellado",
      "Reduce el uso de botellas PET",
      "Repuesto oficial línea Troca Fácil",
    ],
  },
  {
    id: "acquabios-acqua-5",
    name: "ACQUA 5\" Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro compacto 5\" para instalación en línea / pared",
    description:
      "Filtro Acqua 5\" Acquabios para instalación en línea o pared (ideal también junto a la ducha). Compacto de 5\", caudal 60 L/h, retención de partículas Clase D y máxima eficiencia en reducción de cloro libre. Vida útil del cartucho: 4.000 litros (cambiar cada 6 meses o ante baja de caudal). Disponible en cuerpo blanco opaco (BR) o transparente (TR).",
    priceBefore: 0,
    priceNow: 0,
    badge: "5\"",
    badgeTone: "blue",
    note: "Códigos: BR 1000-0019 · TR 1000-0022",
    image: "/products/product-acqua-5-br.png",
    images: [
      "/products/product-acqua-5-br.png",
      "/products/product-acqua-5-tr.png",
      "/products/product-acqua-5-contexto.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
      { label: "1/2\"", icon: "metal" },
    ],
    colors: [
      {
        name: "BR Blanco",
        codes: "1000-0019",
        swatch: "#f5f5f5",
        image: "/products/product-acqua-5-br.png",
      },
      {
        name: "TR Transparente",
        codes: "1000-0022",
        swatch: "#4fc3f7",
        image: "/products/product-acqua-5-tr.png",
      },
    ],
    characteristics: [
      { label: "Código BR", value: "1000-0019" },
      { label: "Código TR", value: "1000-0022" },
      { label: "Presión de operación", value: "19,6 a 392 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca de la tapa", value: "1/2\"" },
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Tamaño", value: "5\"" },
      {
        label: "Clase de retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Vida útil", value: "4.000 litros" },
      {
        label: "Reducción de cloro libre",
        value: "Máxima eficiencia",
      },
    ],
    features: [
      "Instalación en línea / pared (también en ducha)",
      "Máxima eficiencia en reducción de cloro libre",
      "Retención de partículas Clase D",
      "Cambio de cartucho cada 6 meses o ante baja de caudal",
      "Producto certificado",
    ],
  },
  {
    id: "acquabios-acqua-5-torneira",
    name: "Filtro con Grifo ACQUA 5\" Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de mesón 5\" con torneira — BR o TR",
    description:
      "Filtro con grifo Acqua 5\" Acquabios para mesón: misma tecnología de filtración del Acqua 5\" (60 L/h, Clase D, 4.000 litros de vida útil) con base y torneira integrada. Incluye llave de apertura. Disponible en cuerpo blanco (BR) o transparente (TR), con opciones de grifo blanco o cromado.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Con grifo",
    badgeTone: "yellow",
    note: "BR: 1000-0015 / 1000-0001 / 1000-0007 · TR: 1000-0016 / 1000-0004 / 1000-0010",
    image: "/products/product-acqua-5-torneira-br.png",
    images: [
      "/products/product-acqua-5-torneira-br.png",
      "/products/product-acqua-5-torneira-tr.png",
      "/products/product-acqua-5-torneira-contexto.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Mesón", icon: "table" },
      { label: "60 L/h", icon: "bottles" },
      { label: "Con grifo", icon: "metal" },
    ],
    colors: [
      {
        name: "BR Blanco",
        codes: "1000-0015 · grifo blanco 1000-0001 · cromado 1000-0007",
        swatch: "#f5f5f5",
        image: "/products/product-acqua-5-torneira-br.png",
      },
      {
        name: "TR Transparente",
        codes: "1000-0016 · grifo blanco 1000-0004 · cromado 1000-0010",
        swatch: "#4fc3f7",
        image: "/products/product-acqua-5-torneira-tr.png",
      },
    ],
    characteristics: [
      { label: "Código BR (metal)", value: "1000-0015" },
      { label: "Código BR grifo blanco", value: "1000-0001" },
      { label: "Código BR grifo cromado", value: "1000-0007" },
      { label: "Código TR (metal)", value: "1000-0016" },
      { label: "Código TR grifo blanco", value: "1000-0004" },
      { label: "Código TR grifo cromado", value: "1000-0010" },
      { label: "Presión de operación", value: "19,6 a 392 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca de la tapa", value: "1/2\"" },
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Tamaño", value: "5\"" },
      {
        label: "Clase de retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Vida útil", value: "4.000 litros" },
      { label: "Incluye", value: "Llave de apertura (chave)" },
    ],
    features: [
      "Filtro de mesón con grifo integrado",
      "Versiones BR (opaco) y TR (transparente)",
      "Opciones de grifo blanco o cromado",
      "Máxima eficiencia en reducción de cloro libre",
      "Incluye llave de apertura",
      "Producto certificado",
    ],
  },
  {
    id: "acquabios-acqua-230",
    name: "FILTRO ACQUA 230 Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro POU 9 3/4\" — BR o TR",
    description:
      "Filtro Acqua 230 Acquabios para punto de uso: caudal 120 L/h, tamaño 9 3/4\", retención Clase C (5 a 15 μm) y vida útil de 6.000 litros. Máxima eficiencia en reducción de cloro libre. Incluye llave de apertura. Disponible en cuerpo blanco opaco (BR) o transparente (TR).",
    priceBefore: 0,
    priceNow: 0,
    badge: "120 L/h",
    badgeTone: "blue",
    note: "Códigos: BR 1000-0031 · TR 1000-0034",
    image: "/products/product-acqua-230-br.png",
    images: [
      "/products/product-acqua-230-br.png",
      "/products/product-acqua-230-tr.png",
      "/products/product-acqua-230-contexto.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "120 L/h", icon: "bottles" },
      { label: "Clase C", icon: "bolt" },
      { label: "9 3/4\"", icon: "metal" },
    ],
    colors: [
      {
        name: "BR Blanco",
        codes: "1000-0031",
        swatch: "#f5f5f5",
        image: "/products/product-acqua-230-br.png",
      },
      {
        name: "TR Transparente",
        codes: "1000-0034",
        swatch: "#4fc3f7",
        image: "/products/product-acqua-230-tr.png",
      },
    ],
    characteristics: [
      { label: "Código BR", value: "1000-0031" },
      { label: "Código TR", value: "1000-0034" },
      { label: "Presión de operación", value: "19,6 a 392 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca de la tapa", value: "1/2\"" },
      { label: "Caudal", value: "120 litros/hora" },
      { label: "Tamaño", value: "9 3/4\"" },
      {
        label: "Clase de retención de partículas",
        value: "Clase C (5 a 15 μm)",
      },
      { label: "Vida útil", value: "6.000 litros" },
      { label: "Incluye", value: "Llave de apertura" },
    ],
    features: [
      "Ideal para máquinas de café y uso comercial",
      "Versiones BR y TR",
      "Máxima eficiencia en reducción de cloro libre",
      "Incluye llave de apertura",
      "Cambio de cartucho cada 6 meses o ante baja de caudal",
    ],
  },
  {
    id: "acquabios-acqua-200",
    name: "FILTRO ACQUA 200 Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro POU 7\" — BR o TR",
    description:
      "Filtro Acqua 200 Acquabios para punto de uso: caudal 90 L/h, tamaño 7\", retención Clase D (15 a 30 μm) y vida útil de 4.000 litros. Máxima eficiencia en reducción de cloro libre. Incluye llave de apertura. Disponible en BR (blanco) o TR (transparente).",
    priceBefore: 0,
    priceNow: 0,
    badge: "90 L/h",
    badgeTone: "blue",
    note: "Códigos: BR 1000-0025 · TR 1000-0028",
    image: "/products/product-acqua-200-br.png",
    images: [
      "/products/product-acqua-200-br.png",
      "/products/product-acqua-200-tr.png",
      "/products/product-acqua-200-contexto.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "90 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
      { label: "7\"", icon: "metal" },
    ],
    colors: [
      {
        name: "BR Blanco",
        codes: "1000-0025",
        swatch: "#f5f5f5",
        image: "/products/product-acqua-200-br.png",
      },
      {
        name: "TR Transparente",
        codes: "1000-0028",
        swatch: "#4fc3f7",
        image: "/products/product-acqua-200-tr.png",
      },
    ],
    characteristics: [
      { label: "Código BR", value: "1000-0025" },
      { label: "Código TR", value: "1000-0028" },
      { label: "Presión de operación", value: "19,6 a 392 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca de la tapa", value: "1/2\"" },
      { label: "Caudal", value: "90 litros/hora" },
      { label: "Tamaño", value: "7\"" },
      {
        label: "Clase de retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Vida útil", value: "4.000 litros" },
      { label: "Incluye", value: "Llave de apertura" },
    ],
    features: [
      "Instalación en pileta, bebedero o máquina de hielo",
      "Versiones BR y TR",
      "Máxima eficiencia en reducción de cloro libre",
      "Incluye llave de apertura",
      "Cambio de cartucho cada 6 meses o ante baja de caudal",
    ],
  },
  {
    id: "acquabios-refil-carbon-block-5",
    name: "Refil Carbon Block 5\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado — Acqua 5\" BR/TR",
    description:
      "Cartucho Carbon Block 5\" con materias primas especiales de carbón activado que ayuda a impedir la proliferación de bacterias. Alta eficiencia en decloración y retiro de olores y mal sabor. Para filtros Acqua 5\" BR/TR u otras marcas tamaño 5\". Código 1003-0031.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1003-0031",
    image: "/products/product-refil-carbon-block-5.png",
    images: ["/products/product-refil-carbon-block-5.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "5\"", icon: "metal" },
      { label: "60 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
    ],
    characteristics: [
      { label: "Código", value: "1003-0031" },
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Tamaño", value: "5\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      {
        label: "Compatibilidad",
        value: "Acqua 5\" BR/TR y filtros 5\"",
      },
    ],
    features: [
      "Máxima eficiencia en reducción de cloro libre",
      "Retira olores y mal sabor",
      "Carbón activado especial",
    ],
  },
  {
    id: "acquabios-refil-ab100",
    name: "Refil AB 100 Acquabios",
    brand: "Acquabios",
    subtitle: "Refil blindado 5\" — triple filtración",
    description:
      "Refil blindado AB 100 con polipropileno atóxico y carbón activado. Excelente caudal sin pérdida de eficiencia en reducción de cloro, olores y mal sabor. Rosca 1/2\". Triple filtración. Para Acqua 5\" BR/TR u otras marcas 5\". Código 1005-0031.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Triple",
    badgeTone: "blue",
    note: "Código: 1005-0031 · Rosca 1/2\"",
    image: "/products/product-refil-ab100.png",
    images: ["/products/product-refil-ab100.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB 100", icon: "bolt" },
      { label: "5\"", icon: "metal" },
      { label: "60 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0031" },
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Tamaño", value: "5\"" },
      { label: "Rosca", value: "1/2\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Refil blindado de polipropileno atóxico",
      "Triple filtración",
      "Máxima eficiencia en reducción de cloro libre",
    ],
  },
  {
    id: "acquabios-refil-gac-5",
    name: "Refil GAC 5\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado granulado — Acqua 5\"",
    description:
      "Cartucho GAC 5\" fabricado con dos capas de polipropileno y carbón activado granulado. Triple filtración. Para filtros Acqua 5\" BR/TR u otras marcas tamaño 5\". Código 1002-0031.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1002-0031",
    image: "/products/product-refil-gac-5.png",
    images: ["/products/product-refil-gac-5.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "GAC", icon: "bolt" },
      { label: "5\"", icon: "metal" },
      { label: "60 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1002-0031" },
      { label: "Caudal", value: "60 litros/hora" },
      { label: "Tamaño", value: "5\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Dos capas de polipropileno + carbón granulado",
      "Triple filtración",
      "Máxima eficiencia en reducción de cloro libre",
    ],
  },
  {
    id: "acquabios-refil-carbon-block-7",
    name: "Refil Carbon Block 7\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado — Acqua 200 BR/TR",
    description:
      "Cartucho Carbon Block 7\" con carbón activado especial. Alta eficiencia en decloración, olores y mal sabor. Para filtros POU Acqua 200 BR/TR u otras marcas tamaño 7\". Código 1003-0002.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1003-0002",
    image: "/products/product-refil-carbon-block-7.png",
    images: ["/products/product-refil-carbon-block-7.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "7\"", icon: "metal" },
      { label: "90 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
    ],
    characteristics: [
      { label: "Código", value: "1003-0002" },
      { label: "Caudal", value: "90 litros/hora" },
      { label: "Tamaño", value: "7\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      {
        label: "Compatibilidad",
        value: "Acqua 200 BR/TR y filtros 7\"",
      },
    ],
    features: [
      "Máxima eficiencia en reducción de cloro libre",
      "Retira olores y mal sabor",
      "Compatible multimarca 7\"",
    ],
  },
  {
    id: "acquabios-refil-ab200",
    name: "Refil AB 200 Acquabios",
    brand: "Acquabios",
    subtitle: "Refil blindado 7\" — triple filtración",
    description:
      "Refil blindado AB 200 con polipropileno atóxico y carbón activado. Excelente caudal sin pérdida de eficiencia. Rosca 1/2\". Para Acqua 200 BR/TR u otras marcas 7\". Código 1005-0002.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Triple",
    badgeTone: "blue",
    note: "Código: 1005-0002 · Rosca 1/2\"",
    image: "/products/product-refil-ab200.png",
    images: ["/products/product-refil-ab200.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB 200", icon: "bolt" },
      { label: "7\"", icon: "metal" },
      { label: "90 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0002" },
      { label: "Caudal", value: "90 litros/hora" },
      { label: "Tamaño", value: "7\"" },
      { label: "Rosca", value: "1/2\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Refil blindado",
      "Triple filtración",
      "Máxima eficiencia en reducción de cloro libre",
    ],
  },
  {
    id: "acquabios-refil-gac-7",
    name: "Refil GAC 7\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado granulado — Acqua 200",
    description:
      "Cartucho GAC 7\" con dos capas de polipropileno y carbón activado granulado. Triple filtración. Para Acqua 200 BR/TR u otras marcas 7\". Código 1002-0002.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1002-0002",
    image: "/products/product-refil-gac-7.png",
    images: ["/products/product-refil-gac-7.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "GAC", icon: "bolt" },
      { label: "7\"", icon: "metal" },
      { label: "90 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1002-0002" },
      { label: "Caudal", value: "90 litros/hora" },
      { label: "Tamaño", value: "7\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Dos capas de polipropileno + carbón granulado",
      "Triple filtración",
      "Compatible multimarca 7\"",
    ],
  },
  {
    id: "acquabios-refil-carbon-block-975",
    name: "Refil Carbon Block 9 3/4\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado — Acqua 230 BR/TR",
    description:
      "Cartucho Carbon Block 9 3/4\" con carbón activado especial. Alta eficiencia en decloración, olores y mal sabor. Para filtros POU Acqua 230 BR/TR u otras marcas 9 3/4\". Código 1003-0003.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1003-0003",
    image: "/products/product-refil-carbon-block-975.png",
    images: ["/products/product-refil-carbon-block-975.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "9 3/4\"", icon: "metal" },
      { label: "120 L/h", icon: "bottles" },
      { label: "Clase D", icon: "bolt" },
    ],
    characteristics: [
      { label: "Código", value: "1003-0003" },
      { label: "Caudal", value: "120 litros/hora" },
      { label: "Tamaño", value: "9 3/4\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a < 30 μm)",
      },
      {
        label: "Compatibilidad",
        value: "Acqua 230 BR/TR y filtros 9 3/4\"",
      },
    ],
    features: [
      "Máxima eficiencia en reducción de cloro libre",
      "Retira olores y mal sabor",
      "Compatible multimarca 9 3/4\"",
    ],
  },
  {
    id: "acquabios-refil-ab230",
    name: "Refil AB 230 Acquabios",
    brand: "Acquabios",
    subtitle: "Refil blindado 9 3/4\" — triple filtración",
    description:
      "Refil blindado AB 230 con polipropileno atóxico y carbón activado. Excelente caudal sin pérdida de eficiencia. Rosca 1/2\". Para Acqua 230 BR/TR u otras marcas 9 3/4\". Código 1005-0003.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Triple",
    badgeTone: "blue",
    note: "Código: 1005-0003 · Rosca 1/2\"",
    image: "/products/product-refil-ab230.png",
    images: ["/products/product-refil-ab230.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB 230", icon: "bolt" },
      { label: "9 3/4\"", icon: "metal" },
      { label: "120 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1005-0003" },
      { label: "Caudal", value: "120 litros/hora" },
      { label: "Tamaño", value: "9 3/4\"" },
      { label: "Rosca", value: "1/2\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a < 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Refil blindado",
      "Triple filtración",
      "Máxima eficiencia en reducción de cloro libre",
    ],
  },
  {
    id: "acquabios-refil-gac-975",
    name: "Refil GAC 9 3/4\" Acquabios",
    brand: "Acquabios",
    subtitle: "Carbón activado granulado — Acqua 230",
    description:
      "Cartucho GAC 9 3/4\" con dos capas de polipropileno y carbón activado granulado. Triple filtración. Para Acqua 230 BR/TR u otras marcas 9 3/4\". Código 1002-0003.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Repuesto",
    badgeTone: "yellow",
    note: "Código: 1002-0003",
    image: "/products/product-refil-gac-975.png",
    images: ["/products/product-refil-gac-975.png"],
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "GAC", icon: "bolt" },
      { label: "9 3/4\"", icon: "metal" },
      { label: "120 L/h", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código", value: "1002-0003" },
      { label: "Caudal", value: "120 litros/hora" },
      { label: "Tamaño", value: "9 3/4\"" },
      {
        label: "Retención de partículas",
        value: "Clase D (15 a < 30 μm)",
      },
      { label: "Filtración", value: "Triple" },
    ],
    features: [
      "Dos capas de polipropileno + carbón granulado",
      "Triple filtración",
      "Compatible multimarca 9 3/4\"",
    ],
  },
  ...acquabiosExtraProducts,
];

export const specialOfferProducts = catalogProducts.filter((p) => p.featured);

export function getProductById(id: string): ProductOffer | undefined {
  return catalogProducts.find((p) => p.id === id);
}

export function getRelatedProducts(
  product: ProductOffer,
  limit = 4,
): ProductOffer[] {
  const sameCategory = catalogProducts.filter(
    (p) => p.id !== product.id && p.category === product.category,
  );
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit);
  }
  const extras = catalogProducts.filter(
    (p) =>
      p.id !== product.id &&
      p.category !== product.category &&
      !sameCategory.some((s) => s.id === p.id),
  );
  return [...sameCategory, ...extras].slice(0, limit);
}

export function getCategoryLabel(category: ProductOffer["category"]): string {
  return (
    PRODUCT_CATEGORIES.find((c) => c.id === category)?.label ?? category
  );
}
