import type { ProductOffer } from "@/types/product";
import { PRODUCT_CATEGORIES } from "@/types/product";

/**
 * Catálogo importado desde WooCommerce (solo datos útiles).
 * El CSV no traía precios, imágenes ni categorías.
 * Categorías inferidas por nombre; precio "Consultar" hasta completar.
 */
export const catalogProducts: ProductOffer[] = [
  {
    id: "wc-323",
    name: "Dispensador Básico + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-324",
    name: "Dispensador Básico + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-325",
    name: "Dispensador Básico + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-326",
    name: "Dispensador Básico + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-327",
    name: "Bomba Eléctrica USB + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-328",
    name: "Bomba Eléctrica USB + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-329",
    name: "Bomba Eléctrica USB + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-330",
    name: "Bomba Eléctrica USB + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-332",
    name: "Recarga de 20 lt",
    priceBefore: 2500,
    priceNow: 2500,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-333",
    name: "Envase + Recarga de 20 lt",
    priceBefore: 5800,
    priceNow: 5000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-334",
    name: "5 Recargas de 20 lt c/u",
    priceBefore: 14000,
    priceNow: 12500,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-337",
    name: "Bomba Electrónica USB",
    priceBefore: 7000,
    priceNow: 2700,
    badge: "-61%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "bombas",
    inStock: true,
    tags: [
      { label: "USB", icon: "bolt" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-338",
    name: "Dispensador Básico",
    priceBefore: 7000,
    priceNow: 5000,
    badge: "-29%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-848",
    name: "Dispensador con filtro de sistema osmosis inversa",
    description: "Dispensador de agua sistema OSMOSIS INVERSA, no ocupa bidones ya que purifica y filtra el agua potable, conectado directo a una llave de red potable. Dispensa agua en 3 temperat…",
    priceBefore: 320000,
    priceNow: 297500,
    badge: "-7%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-851",
    name: "Filtro sistema osmosis inversa",
    description: "Filtro de osmosis inversa Agua Ser purificada. Mejora la calidad y sabor del agua de tu casa, filtro se instala debajo del lavaplatos. Elimina el 90% de las partículas, sustanci…",
    priceBefore: 120000,
    priceNow: 95000,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-960",
    name: "Recarga PACK 12unidades de agua gasificada 500cc",
    description: "Pack 12 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-997",
    name: "Recarga PACK 6unidades agua gasificada 1.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4200,
    priceNow: 4200,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-999",
    name: "Recarga PACK 6unidades de agua gasificada 2.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1001",
    name: "Recarga PACK 6unidades de agua gasificada 3lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 6000,
    priceNow: 6000,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1003",
    name: "Compresor para dispensador",
    priceBefore: 56000,
    priceNow: 55000,
    badge: "-2%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1541",
    name: "Soporte para Bidones",
    description: "Reemplazo universal para dispensadores de agua frío/calor 17 cm diametro. ($9.990 c/u) ENVIOS NO INCLUIDO, SE CALCULA DEPENDIENDO COMUNA",
    priceBefore: 15990,
    priceNow: 9990,
    badge: "-38%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1546",
    name: "Racks para 5 Bidones de 20 lts",
    description: "Capacidad para 5 bidones",
    priceBefore: 54000,
    priceNow: 40000,
    badge: "-26%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1549",
    name: "Llaves de repuesto para dispensadores frío/calor de pedestal",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1553",
    name: "Llaves de repuesto para dispensadores frío/calor de sobremesa",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1564",
    name: "Bidón completo de 10 lts",
    priceBefore: 3900,
    priceNow: 3900,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1569",
    name: "Recarga bidón de 10 lts",
    priceBefore: 2200,
    priceNow: 1800,
    badge: "-18%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1571",
    name: "Dispensador de Sobremesa para agua fría y caliente",
    description: "Grados de la máquina: Agua caliente 85°c-95°c Agua fría 10°c-15°c",
    priceBefore: 50000,
    priceNow: 39000,
    badge: "-22%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-1590",
    name: "Dispensador de Pedestal 2 llaves con sistema compresor",
    priceBefore: 137000,
    priceNow: 137000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1930",
    name: "Dispensador Pedestal 3 Llaves Con Sistema Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 143000,
    priceNow: 143000,
    badge: "Destacado",
    badgeTone: "yellow",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    featured: true,
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1937",
    name: "Rack Para 3 Bidones 20l",
    priceBefore: 35000,
    priceNow: 30000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1941",
    name: "Rack Para 2 Bidones 20l",
    priceBefore: 20000,
    priceNow: 20000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1944",
    name: "Tapas Para Bidones De 20l Y 10l",
    priceBefore: 100,
    priceNow: 72,
    badge: "-28%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1947",
    name: "Manilla Sujetadora De Bidones",
    priceBefore: 2000,
    priceNow: 1500,
    badge: "-25%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1981",
    name: "Hielo 1 kg",
    description: "Hielo de agua purificada 1 kilo SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 800,
    priceNow: 600,
    badge: "-25%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1984",
    name: "Hielo 2 kg",
    description: "Hielo de agua purificada 2 kilos SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1987",
    name: "Rack Para 3 Bidones 20 Litros",
    description: "RACK SOPORTE PARA 3 BIDONES 20 LITROS",
    priceBefore: 30000,
    priceNow: 18000,
    badge: "-40%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2341",
    name: "Dispensador Sobremesa Agua Fría Y Caliente",
    description: "DISPENSADOR ELECTRICO DE SOBREMESA, CON SISTEMA VENTILADOR, AGUA FRIA ENTRE 10 Y 15 GRADOS Y AGUA CALIENTE ENTRE 85 Y 90 GRADOS °C.",
    priceBefore: 50000,
    priceNow: 45000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-2346",
    name: "Dispensador Digital de Té Incluye Tetera Y Hervidor",
    description: "DISPENSADOR DIGITAL AUTOMATICO DE TE INCLUYE ACCESORIOS TETERA Y HERVIDOR COMPARTIMIENTO INFERIOR PARA BIDON DE 20 LITROS",
    priceBefore: 100000,
    priceNow: 80000,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/product-tea-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2354",
    name: "Bidón Desechable 6 Litros",
    description: "BIDON DESECHABLE 6 LITROS",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "6 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2444",
    name: "Dispensador Pedestal 3 Llaves Con Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 170000,
    priceNow: 154700,
    badge: "-9%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-2447",
    name: "Dispensador Pedestal 2 Llaves Con Frigobar",
    description: "Dispensador pedestal 2 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 90°c. Con motor compresor. Compartimiento enfría tus bebidas.",
    priceBefore: 150000,
    priceNow: 130900,
    badge: "-13%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2579",
    name: "Servicio Instalación Dispensador Ósmosis",
    description: "Contamos con servicio de instalación a domicilio (solo para Santiago, RM) para dispensador osmosis. Para mayor información por favor comunicarse al +56944786330",
    priceBefore: 40000,
    priceNow: 35700,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "servicios",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
      { label: "Santiago RM", icon: "map" },
    ],
  },
];

export const specialOfferProducts = catalogProducts.filter((p) => p.featured);

export function getProductById(id: string): ProductOffer | undefined {
  return catalogProducts.find((p) => p.id === id);
}

export function getRelatedProducts(
  product: ProductOffer,
  limit = 4,
): ProductOffer[] {
  const sameCategory = catalogProducts.filter(
    (p) => p.id !== product.id && p.category === product.category,
  );
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit);
  }
  const extras = catalogProducts.filter(
    (p) =>
      p.id !== product.id &&
      p.category !== product.category &&
      !sameCategory.some((s) => s.id === p.id),
  );
  return [...sameCategory, ...extras].slice(0, limit);
}

export function getCategoryLabel(category: ProductOffer["category"]): string {
  return (
    PRODUCT_CATEGORIES.find((c) => c.id === category)?.label ?? category
  );
}
