import type { ProductOffer } from "@/types/product";
import { PRODUCT_CATEGORIES } from "@/types/product";

/**
 * Catálogo importado desde WooCommerce (solo datos útiles).
 * El CSV no traía precios, imágenes ni categorías.
 * Categorías inferidas por nombre; precio "Consultar" hasta completar.
 */
export const catalogProducts: ProductOffer[] = [
  {
    id: "wc-323",
    name: "Dispensador Básico + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-324",
    name: "Dispensador Básico + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-325",
    name: "Dispensador Básico + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-326",
    name: "Dispensador Básico + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-327",
    name: "Bomba Eléctrica USB + 1 Bidón de 20 lt con envase",
    priceBefore: 12000,
    priceNow: 9500,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-328",
    name: "Bomba Eléctrica USB + 2 Bidones de 20 lt con envase",
    priceBefore: 15000,
    priceNow: 12500,
    badge: "-17%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-329",
    name: "Bomba Eléctrica USB + 3 Bidones de 20 lt con envase",
    priceBefore: 18000,
    priceNow: 15500,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-330",
    name: "Bomba Eléctrica USB + 4 Bidones 20 lt con envase",
    priceBefore: 20000,
    priceNow: 18000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "blue",
    category: "combos",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "USB", icon: "bolt" },
    ],
  },
  {
    id: "wc-332",
    name: "Recarga de 20 lt",
    priceBefore: 2500,
    priceNow: 2500,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-333",
    name: "Envase + Recarga de 20 lt",
    priceBefore: 5800,
    priceNow: 5000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-334",
    name: "5 Recargas de 20 lt c/u",
    priceBefore: 14000,
    priceNow: 12500,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-337",
    name: "Bomba Electrónica USB",
    priceBefore: 7000,
    priceNow: 2700,
    badge: "-61%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "bombas",
    inStock: true,
    tags: [
      { label: "USB", icon: "bolt" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-338",
    name: "Dispensador Básico",
    priceBefore: 7000,
    priceNow: 5000,
    badge: "-29%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-848",
    name: "Dispensador con filtro de sistema osmosis inversa",
    description: "Dispensador de agua sistema OSMOSIS INVERSA, no ocupa bidones ya que purifica y filtra el agua potable, conectado directo a una llave de red potable. Dispensa agua en 3 temperat…",
    priceBefore: 320000,
    priceNow: 297500,
    badge: "-7%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-851",
    name: "Filtro sistema osmosis inversa",
    description: "Filtro de osmosis inversa Agua Ser purificada. Mejora la calidad y sabor del agua de tu casa, filtro se instala debajo del lavaplatos. Elimina el 90% de las partículas, sustanci…",
    priceBefore: 120000,
    priceNow: 95000,
    badge: "-21%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "filtracion",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
    ],
  },
  {
    id: "wc-960",
    name: "Recarga PACK 12unidades de agua gasificada 500cc",
    description: "Pack 12 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-997",
    name: "Recarga PACK 6unidades agua gasificada 1.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4200,
    priceNow: 4200,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-999",
    name: "Recarga PACK 6unidades de agua gasificada 2.5lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 4800,
    priceNow: 4800,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1001",
    name: "Recarga PACK 6unidades de agua gasificada 3lt",
    description: "Pack 6 unidades / Solo retiro en local.",
    priceBefore: 6000,
    priceNow: 6000,
    badge: "Disponible",
    badgeTone: "blue",
    note: "Solo retiro en local",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "Retiro en local", icon: "map" },
    ],
  },
  {
    id: "wc-1003",
    name: "Compresor para dispensador",
    priceBefore: 56000,
    priceNow: 55000,
    badge: "-2%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1541",
    name: "Soporte para Bidones",
    description: "Reemplazo universal para dispensadores de agua frío/calor 17 cm diametro. ($9.990 c/u) ENVIOS NO INCLUIDO, SE CALCULA DEPENDIENDO COMUNA",
    priceBefore: 15990,
    priceNow: 9990,
    badge: "-38%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1546",
    name: "Racks para 5 Bidones de 20 lts",
    description: "Capacidad para 5 bidones",
    priceBefore: 54000,
    priceNow: 40000,
    badge: "-26%",
    badgeTone: "green",
    note: "No Incluye Envío",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1549",
    name: "Llaves de repuesto para dispensadores frío/calor de pedestal",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1553",
    name: "Llaves de repuesto para dispensadores frío/calor de sobremesa",
    priceBefore: 15000,
    priceNow: 12000,
    badge: "-20%",
    badgeTone: "green",
    note: "No Incluye Costos De Envío",
    image: "/products/product-countertop-dispenser.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "Envío aparte", icon: "truck" },
    ],
  },
  {
    id: "wc-1564",
    name: "Bidón completo de 10 lts",
    priceBefore: 3900,
    priceNow: 3900,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1569",
    name: "Recarga bidón de 10 lts",
    priceBefore: 2200,
    priceNow: 1800,
    badge: "-18%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1571",
    name: "Dispensador de Sobremesa para agua fría y caliente",
    description: "Grados de la máquina: Agua caliente 85°c-95°c Agua fría 10°c-15°c",
    priceBefore: 50000,
    priceNow: 39000,
    badge: "-22%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-1590",
    name: "Dispensador de Pedestal 2 llaves con sistema compresor",
    priceBefore: 137000,
    priceNow: 137000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1930",
    name: "Dispensador Pedestal 3 Llaves Con Sistema Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 143000,
    priceNow: 143000,
    badge: "Destacado",
    badgeTone: "yellow",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    featured: true,
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1937",
    name: "Rack Para 3 Bidones 20l",
    priceBefore: 35000,
    priceNow: 30000,
    badge: "-14%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1941",
    name: "Rack Para 2 Bidones 20l",
    priceBefore: 20000,
    priceNow: 20000,
    badge: "Disponible",
    badgeTone: "blue",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1944",
    name: "Tapas Para Bidones De 20l Y 10l",
    priceBefore: 100,
    priceNow: 72,
    badge: "-28%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: false,
    tags: [
      { label: "20 litros", icon: "bottles" },
      { label: "10 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-1947",
    name: "Manilla Sujetadora De Bidones",
    priceBefore: 2000,
    priceNow: 1500,
    badge: "-25%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-1981",
    name: "Hielo 1 kg",
    description: "Hielo de agua purificada 1 kilo SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 800,
    priceNow: 600,
    badge: "-25%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1984",
    name: "Hielo 2 kg",
    description: "Hielo de agua purificada 2 kilos SOLO DISPONIBLE COMUNA MAIPU",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    note: "Solo Maipú",
    image: "/products/product-ice-2kg.png",
    tint: "blue",
    category: "consumibles",
    inStock: true,
    tags: [
      { label: "Solo Maipú", icon: "map" },
    ],
  },
  {
    id: "wc-1987",
    name: "Rack Para 3 Bidones 20 Litros",
    description: "RACK SOPORTE PARA 3 BIDONES 20 LITROS",
    priceBefore: 30000,
    priceNow: 18000,
    badge: "-40%",
    badgeTone: "green",
    image: "/products/product-rack-bidones.png",
    tint: "yellow",
    category: "accesorios",
    inStock: true,
    tags: [
      { label: "20 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2341",
    name: "Dispensador Sobremesa Agua Fría Y Caliente",
    description: "DISPENSADOR ELECTRICO DE SOBREMESA, CON SISTEMA VENTILADOR, AGUA FRIA ENTRE 10 Y 15 GRADOS Y AGUA CALIENTE ENTRE 85 Y 90 GRADOS °C.",
    priceBefore: 50000,
    priceNow: 45000,
    badge: "-10%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [
      { label: "Frío y caliente", icon: "snowflake" },
    ],
  },
  {
    id: "wc-2346",
    name: "Dispensador Digital de Té Incluye Tetera Y Hervidor",
    description: "DISPENSADOR DIGITAL AUTOMATICO DE TE INCLUYE ACCESORIOS TETERA Y HERVIDOR COMPARTIMIENTO INFERIOR PARA BIDON DE 20 LITROS",
    priceBefore: 100000,
    priceNow: 80000,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/product-tea-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2354",
    name: "Bidón Desechable 6 Litros",
    description: "BIDON DESECHABLE 6 LITROS",
    priceBefore: 1500,
    priceNow: 1200,
    badge: "-20%",
    badgeTone: "green",
    image: "/products/hero-jug-splash.png",
    tint: "blue",
    category: "recargas",
    inStock: true,
    tags: [
      { label: "6 litros", icon: "bottles" },
    ],
  },
  {
    id: "wc-2444",
    name: "Dispensador Pedestal 3 Llaves Con Compresor",
    description: "Dispensador pedestal 3 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 95°c, y agua temperatura ambiente. Con motor compresor. Compartimiento no enfría.",
    priceBefore: 170000,
    priceNow: 154700,
    badge: "-9%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: true,
    tags: [],
  },
  {
    id: "wc-2447",
    name: "Dispensador Pedestal 2 Llaves Con Frigobar",
    description: "Dispensador pedestal 2 llaves: agua fría entre 5° y 10°c, agua caliente entre 85° y 90°c. Con motor compresor. Compartimiento enfría tus bebidas.",
    priceBefore: 150000,
    priceNow: 130900,
    badge: "-13%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "dispensadores",
    inStock: false,
    tags: [],
  },
  {
    id: "wc-2579",
    name: "Servicio Instalación Dispensador Ósmosis",
    description: "Contamos con servicio de instalación a domicilio (solo para Santiago, RM) para dispensador osmosis. Para mayor información por favor comunicarse al +56944786330",
    priceBefore: 40000,
    priceNow: 35700,
    badge: "-11%",
    badgeTone: "green",
    image: "/products/product-countertop-dispenser.png",
    tint: "green",
    category: "servicios",
    inStock: true,
    tags: [
      { label: "Ósmosis", icon: "bolt" },
      { label: "Santiago RM", icon: "map" },
    ],
  },
  {
    id: "acquabios-ultra-ice",
    name: "ULTRA ICE Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador de agua — fría y temperatura ambiente",
    description:
      "Compacto y altamente eficiente. Su depósito es ultra-resistente a la presión del agua y antibacteriano, con un moderno sistema de refrigeración por compresor. Ideal para hogar u oficina: agua natural y fría en un solo equipo.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Códigos: 1008-0181 (220V) / 1008-0182 (127V)",
    image: "/products/product-ultra-ice-negro.png",
    images: [
      "/products/product-ultra-ice-negro.png",
      "/products/product-ultra-ice-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Agua fría", icon: "snowflake" },
      { label: "Temperatura ambiente", icon: "kettle" },
      { label: "Compresor", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo del agua", value: "60 litros por hora" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      { label: "Retención de partículas", value: "de >0,5 a <1 μm" },
      {
        label: "Vida útil del cartucho",
        value: "2.500 litros o 6 meses",
      },
      {
        label: "Capacidad de refrigeración",
        value: "2,2 litros por hora",
      },
      {
        label: "Volumen interno del reservorio",
        value: "2,3 litros",
      },
    ],
    features: [
      "Sistema de refrigeración por compresor",
      "Cartucho de fácil sustitución: gira y cambia",
      "Cartucho ultra duradero",
      "Luz indicadora para el reemplazo del cartucho",
      "Reservorio antibacterial y ultra resistente",
      "Bajo consumo de energía",
      "Calidad comprobada",
    ],
    specs: [
      { label: "Voltaje (V)", value: "220V / 110V" },
      { label: "Potencia (W)", value: "80W / 100W" },
      { label: "Frecuencia (Hz)", value: "50–60 Hz / 60 Hz" },
    ],
    colors: [
      {
        name: "Blanco",
        codes: "1008-0179 (220V) / 1008-0180 (127V)",
        swatch: "#f4f6f8",
        image: "/products/product-ultra-ice-blanco.png",
      },
      {
        name: "Negro",
        codes: "1008-0181 (220V) / 1008-0182 (127V)",
        swatch: "#1a1a1a",
        image: "/products/product-ultra-ice-negro.png",
      },
      {
        name: "Plata",
        codes: "1008-0183 (220V) / 1008-0184 (127V)",
        swatch: "#c5ccd3",
      },
    ],
  },
  {
    id: "acquabios-easy",
    name: "EASY Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador de agua natural",
    description:
      "Los colores sólidos fueron diseñados para combinar con las líneas de electrodomésticos, de esta forma el depurador se integra en la decoración. Purificador de mesa con sistema de intercambio fácil de cartucho y agua pura con un clic. Certificación INMETRO de desempeño en reducción de cloro y retención de partículas.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1008-0013 (Negro)",
    image: "/products/product-easy-negro.png",
    images: [
      "/products/product-easy-negro.png",
      "/products/product-easy-rojo.png",
      "/products/product-easy-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Agua natural", icon: "bottles" },
      { label: "Sobremesa", icon: "table" },
      { label: "Fácil recambio", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo del agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "de ≥5 a <15 μm",
      },
      {
        label: "Vida útil del cartucho",
        value: "1.500 litros o 6 meses",
      },
      { label: "Instalación", value: "Mesa (sobremesa)" },
    ],
    features: [
      "Sistema de intercambio fácil (Easy Replacement System)",
      "Agua pura con un clic (Pure Water One Click)",
      "Diseño para combinar con electrodomésticos",
      "Cartucho de fácil sustitución",
      "Certificación INMETRO de desempeño",
      "Instalación en mesa, compacto y discreto",
    ],
    colors: [
      {
        name: "Negro",
        codes: "1008-0013",
        swatch: "#1a1a1a",
        image: "/products/product-easy-negro.png",
      },
      {
        name: "Rojo",
        codes: "1008-0014",
        swatch: "#c62828",
        image: "/products/product-easy-rojo.png",
      },
      {
        name: "Blanco",
        codes: "1008-0012",
        swatch: "#f4f6f8",
        image: "/products/product-easy-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-easy-special",
    name: "EASY Special Edition Acquabios",
    brand: "Acquabios",
    subtitle: "Purificador de agua natural — edición especial",
    description:
      "Desarrollado siguiendo las tendencias globales en diseño y acabados, asegurando belleza y ambientes contemporáneos. Misma tecnología del EASY con acabados metálicos premium. Incluye llave de reemplazo de cartucho y válvula de instalación compatible con tubería de 1/2\" y salida de manguera de 1/4\".",
    priceBefore: 0,
    priceNow: 0,
    badge: "Edición especial",
    badgeTone: "yellow",
    note: "Código principal: 1008-0015 (Rose Gold)",
    image: "/products/product-easy-special-rosegold.png",
    images: [
      "/products/product-easy-special-rosegold.png",
      "/products/product-easy-special-gris.png",
    ],
    tint: "yellow",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Agua natural", icon: "bottles" },
      { label: "Edición especial", icon: "metal" },
      { label: "Sobremesa", icon: "table" },
    ],
    characteristics: [
      { label: "Flujo del agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "de ≥5 a <15 μm",
      },
      {
        label: "Vida útil del cartucho",
        value: "1.500 litros o 6 meses",
      },
      { label: "Instalación", value: "Mesa (sobremesa)" },
    ],
    features: [
      "Acabados metálicos premium (tendencia global)",
      "Sistema de intercambio fácil de cartucho",
      "Agua pura con un clic",
      "Incluye llave de reemplazo",
      "Incluye válvula de instalación 1/2\" → 1/4\"",
      "Certificación INMETRO de desempeño",
    ],
    colors: [
      {
        name: "Rose Gold",
        codes: "1008-0015",
        swatch: "#b76e79",
        image: "/products/product-easy-special-rosegold.png",
      },
      {
        name: "Gris",
        codes: "1008-0026",
        swatch: "#6b7280",
        image: "/products/product-easy-special-gris.png",
      },
    ],
  },
  {
    id: "acquabios-easy-cartucho",
    name: "Cartucho de reposición EASY Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho de filtración para línea EASY",
    description:
      "Cartucho de reposición oficial para purificadores Acquabios EASY y EASY Special Edition. Mantiene el flujo, la reducción de cloro/olor/mal sabor y la retención de partículas del equipo. Código 1005-0047.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Consumible",
    badgeTone: "blue",
    note: "Código: 1005-0047",
    image: "/products/product-easy-cartucho.png",
    images: ["/products/product-easy-cartucho.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "Repuesto", icon: "bolt" },
      { label: "1.500 litros", icon: "bottles" },
    ],
    characteristics: [
      { label: "Flujo", value: "40 L/h" },
      { label: "Vida útil", value: "1.500 litros o 6 meses" },
      {
        label: "Compatibilidad",
        value: "EASY y EASY Special Edition",
      },
      { label: "Código", value: "1005-0047" },
    ],
    features: [
      "Repuesto oficial Acquabios",
      "Compatible con EASY y Special Edition",
      "Fácil sustitución en el equipo",
      "Mantiene el desempeño de filtración",
    ],
  },
  {
    id: "acquabios-premium-grifo",
    name: "Premium Filtro con Grifo Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo integrado",
    description:
      "Tu cocina merece la Premium. Filtro con grifo de pared Acquabios: reduce cloro, olor y mal sabor, con volantes ergonómicos de apertura fácil (1/4 de vuelta). Diseño compacto para instalar en muro. Certificación INMETRO de desempeño. Envase tipo blister para gancho; caja con 4 unidades.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0022 (Negro / Rose Gold)",
    image: "/products/product-premium-negro-rosegold.png",
    images: [
      "/products/product-premium-negro-rosegold.png",
      "/products/product-premium-blanco-rosegold.png",
      "/products/product-premium-negro-cromo.png",
      "/products/product-premium-rojo-rosegold.png",
      "/products/product-premium-blanco-azul.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Apertura fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      {
        label: "Apertura",
        value: "Fácil, 1/4 de vuelta",
      },
    ],
    features: [
      "Filtro con grifo integrado",
      "Abre fácil: 1/4 de vuelta",
      "Volantes ergonómicos, eficientes y durables",
      "Instalación de pared",
      "Reducción de cloro, olor y mal sabor",
      "Certificación INMETRO de desempeño",
    ],
    colors: [
      {
        name: "Negro / Rose Gold",
        codes: "1006-0022",
        swatch: "#1a1a1a",
        image: "/products/product-premium-negro-rosegold.png",
      },
      {
        name: "Blanco / Rose Gold",
        codes: "1006-0023",
        swatch: "#f4f6f8",
        image: "/products/product-premium-blanco-rosegold.png",
      },
      {
        name: "Negro / Cromo",
        codes: "1019-0003",
        swatch: "#2a2a2a",
        image: "/products/product-premium-negro-cromo.png",
      },
      {
        name: "Rojo / Rose Gold",
        codes: "1006-0072",
        swatch: "#c62828",
        image: "/products/product-premium-rojo-rosegold.png",
      },
      {
        name: "Blanco / Azul",
        codes: "1006-0024",
        swatch: "#2f6fed",
        image: "/products/product-premium-blanco-azul.png",
      },
    ],
  },
  {
    id: "acquabios-filtro-mesa",
    name: "Filtro con Grifo de Mesa Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de mesa con grifo — abre fácil",
    description:
      "Filtro con grifo de mesa Acquabios: reduce cloro, olor y mal sabor, con apertura fácil y diseño compacto para instalar sobre el mesón. Flujo de 40 L/h y cartucho de larga duración. Certificación INMETRO de desempeño y sello de calidad y tecnología.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0145 (Cromo)",
    image: "/products/product-filtro-mesa-cromo.png",
    images: [
      "/products/product-filtro-mesa-cromo.png",
      "/products/product-filtro-mesa-negro.png",
      "/products/product-filtro-mesa-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De mesa", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Abre fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "Mesa (sobremesa)" },
      { label: "Apertura", value: "Abre fácil" },
    ],
    features: [
      "Filtro con grifo de mesa",
      "Sistema abre fácil",
      "Reducción de cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho AB40",
    ],
    colors: [
      {
        name: "Cromo",
        codes: "1006-0145",
        swatch: "#c0c5cc",
        image: "/products/product-filtro-mesa-cromo.png",
      },
      {
        name: "Negro",
        codes: "1006-0144",
        swatch: "#1a1a1a",
        image: "/products/product-filtro-mesa-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0143",
        swatch: "#f4f6f8",
        image: "/products/product-filtro-mesa-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-filtro-pared",
    name: "Filtro con Grifo de Pared Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo — abre fácil",
    description:
      "Filtro con grifo de pared Acquabios: misma tecnología de filtración en formato mural. Reduce cloro, olor y mal sabor, con apertura fácil. Ideal cuando prefieres instalación en muro. Certificación INMETRO de desempeño.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0141 (Cromo)",
    image: "/products/product-filtro-pared-cromo.png",
    images: [
      "/products/product-filtro-pared-cromo.png",
      "/products/product-filtro-pared-negro.png",
      "/products/product-filtro-pared-blanco.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Con grifo", icon: "bottles" },
      { label: "Abre fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      { label: "Apertura", value: "Abre fácil" },
    ],
    features: [
      "Filtro con grifo de pared",
      "Sistema abre fácil",
      "Reducción de cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho AB40",
    ],
    colors: [
      {
        name: "Cromo",
        codes: "1006-0141",
        swatch: "#c0c5cc",
        image: "/products/product-filtro-pared-cromo.png",
      },
      {
        name: "Negro",
        codes: "1006-0140",
        swatch: "#1a1a1a",
        image: "/products/product-filtro-pared-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0139",
        swatch: "#f4f6f8",
        image: "/products/product-filtro-pared-blanco.png",
      },
    ],
  },
  {
    id: "acquabios-cartucho-ab40",
    name: "Cartucho de reposición AB40 Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho AB40 — triple filtración",
    description:
      "Cartucho de reposición Acquabios AB40 para filtros con grifo de mesa y de pared. Triple filtración, alta eficiencia en retención de partículas y reducción de cloro, olor y mal sabor. Viene con un cartucho adicional gratis. Código 1005-0006.",
    priceBefore: 0,
    priceNow: 0,
    badge: "2x1",
    badgeTone: "yellow",
    note: "Código: 1005-0006 · Incluye cartucho adicional gratis",
    image: "/products/product-cartucho-ab40.png",
    images: ["/products/product-cartucho-ab40.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "AB40", icon: "bolt" },
      { label: "Triple filtración", icon: "bottles" },
      { label: "1.500 litros", icon: "bottles" },
    ],
    characteristics: [
      { label: "Modelo", value: "AB40" },
      { label: "Código", value: "1005-0006" },
      { label: "Filtración", value: "Triple" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Alta eficiencia",
      },
      {
        label: "Compatibilidad",
        value: "Filtro grifo de mesa y de pared",
      },
    ],
    features: [
      "Triple filtración",
      "Alta eficiencia en retención de partículas",
      "Reduce cloro, olor y mal sabor",
      "Incluye un cartucho adicional gratis",
      "Repuesto oficial Acquabios AB40",
    ],
  },
  {
    id: "acquabios-colors",
    name: "COLORS Filtro con Grifo de Pared Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de pared con grifo — ¡un toque de color y todo cambia!",
    description:
      "Línea COLORS de Acquabios: filtro con grifo de pared en colores vibrantes. Sistema de recambio fácil sin herramientas, reduce cloro, olor y mal sabor, y retiene partículas clase D. Ideal para dar un toque de color a la cocina. Envase blister para gancho; caja con 6 unidades. Certificación INMETRO y sello de calidad y tecnología.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1006-0092 (Negro)",
    image: "/products/product-colors-negro.png",
    images: [
      "/products/product-colors-negro.png",
      "/products/product-colors-blanco.png",
      "/products/product-colors-azul.png",
      "/products/product-colors-rojo.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "De pared", icon: "table" },
      { label: "Colores", icon: "metal" },
      { label: "Recambio fácil", icon: "bolt" },
    ],
    characteristics: [
      { label: "Flujo de agua", value: "40 L/h" },
      {
        label: "Reducción de cloro, olor y mal sabor",
        value: "Sí",
      },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      { label: "Vida útil del cartucho", value: "1.500 litros" },
      { label: "Instalación", value: "De pared" },
      {
        label: "Recambio",
        value: "Sistema fácil, sin herramientas",
      },
    ],
    features: [
      "Un toque de color y todo cambia",
      "Sistema de intercambio fácil de cartucho",
      "Filtro con grifo de pared integrado",
      "Reducción de cloro, olor y mal sabor",
      "Certificación INMETRO de desempeño",
      "Compatible con cartucho COLORS",
    ],
    colors: [
      {
        name: "Negro",
        codes: "1006-0092",
        swatch: "#1a1a1a",
        image: "/products/product-colors-negro.png",
      },
      {
        name: "Blanco",
        codes: "1006-0001",
        swatch: "#f4f6f8",
        image: "/products/product-colors-blanco.png",
      },
      {
        name: "Azul",
        codes: "1006-0002",
        swatch: "#1e6fd9",
        image: "/products/product-colors-azul.png",
      },
      {
        name: "Rojo",
        codes: "1006-0003",
        swatch: "#c62828",
        image: "/products/product-colors-rojo.png",
      },
    ],
  },
  {
    id: "acquabios-colors-cartucho",
    name: "Cartucho de reposición COLORS Acquabios",
    brand: "Acquabios",
    subtitle: "Cartucho para línea COLORS",
    description:
      "Cartucho de reposición oficial para filtros COLORS Acquabios. Flujo 40 L/h, vida útil 1.500 litros y retención de partículas clase D. Un cartucho equivale a aproximadamente 75 galones de agua (cerca de 20 bidones de 20 L). Código 1007-0001. También disponibles carcasas de reposición en rojo (1007-0003) y negro (1007-0004).",
    priceBefore: 0,
    priceNow: 0,
    badge: "Consumible",
    badgeTone: "blue",
    note: "Código: 1007-0001 · Carcasas: 1007-0003 (rojo) / 1007-0004 (negro)",
    image: "/products/product-colors-cartucho.png",
    images: ["/products/product-colors-cartucho.png"],
    tint: "blue",
    category: "consumibles",
    featured: true,
    inStock: true,
    tags: [
      { label: "COLORS", icon: "bolt" },
      { label: "1.500 litros", icon: "bottles" },
      { label: "Repuesto", icon: "bottles" },
    ],
    characteristics: [
      { label: "Código cartucho", value: "1007-0001" },
      { label: "Flujo", value: "40 L/h" },
      { label: "Vida útil", value: "1.500 litros" },
      {
        label: "Retención de partículas",
        value: "Clase D (≥15 a <30 μm)",
      },
      {
        label: "Equivalencia",
        value: "≈ 75 galones / ~20 bidones de 20 L",
      },
      {
        label: "Compatibilidad",
        value: "Línea COLORS Acquabios",
      },
    ],
    features: [
      "Repuesto oficial línea COLORS",
      "Recambio fácil en el equipo",
      "Reduce cloro, olor y mal sabor",
      "Alta eficiencia en retención de partículas",
      "Carcasas opcionales rojo y negro",
    ],
  },
  {
    id: "acquabios-grifo-bano",
    name: "Grifo de Mesa para Baño Acquabios",
    brand: "Acquabios",
    subtitle: "Grifería para lavamanos — abre fácil 1/4 de vuelta",
    description:
      "Los baños también siguen las tendencias. Grifo de mesa para baño Acquabios con cuello de cisne elegante, llave de cuatro asas (cuadriseta) y apertura fácil de 1/4 de vuelta. Ideal para lavamanos tipo vessel o vanitory. Acabados en tendencia para un baño más elegante.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Nuevo",
    badgeTone: "green",
    note: "Código principal: 1020-0012 (Rojo)",
    image: "/products/product-grifo-bano-rojo.png",
    images: [
      "/products/product-grifo-bano-rojo.png",
      "/products/product-grifo-bano-cromo.png",
      "/products/product-grifo-bano-blanco.png",
      "/products/product-grifo-bano-gris.png",
      "/products/product-grifo-bano-negro.png",
    ],
    tint: "blue",
    category: "accesorios",
    featured: true,
    inStock: true,
    tags: [
      { label: "Para baño", icon: "table" },
      { label: "Abre fácil", icon: "bolt" },
      { label: "Cuello de cisne", icon: "metal" },
    ],
    characteristics: [
      { label: "Tipo", value: "Grifo de mesa para baño" },
      { label: "Instalación", value: "Sobre mesón / lavamanos" },
      {
        label: "Apertura",
        value: "Fácil, 1/4 de vuelta",
      },
      {
        label: "Llave",
        value: "Cuatro asas (cuadriseta)",
      },
      {
        label: "Diseño",
        value: "Cuello de cisne alto",
      },
    ],
    features: [
      "Abre fácil: 1/4 de vuelta",
      "Llave cuatro asas (cuadriseta)",
      "Diseño elegante cuello de cisne",
      "Ideal para lavamanos y vanitory",
      "Variedad de colores en tendencia",
      "Base y manilla en cromo pulido",
    ],
    colors: [
      {
        name: "Blanco",
        codes: "1020-0008",
        swatch: "#f4f6f8",
        image: "/products/product-grifo-bano-blanco.png",
      },
      {
        name: "Gris",
        codes: "1020-0009",
        swatch: "#9aa3ad",
        image: "/products/product-grifo-bano-gris.png",
      },
      {
        name: "Cromo",
        codes: "1020-0010",
        swatch: "#c0c5cc",
        image: "/products/product-grifo-bano-cromo.png",
      },
      {
        name: "Negro",
        codes: "1020-0011",
        swatch: "#1a1a1a",
        image: "/products/product-grifo-bano-negro.png",
      },
      {
        name: "Rojo",
        codes: "1020-0012",
        swatch: "#c62828",
        image: "/products/product-grifo-bano-rojo.png",
      },
    ],
  },
  {
    id: "acquabios-acqua-blue",
    name: "ACQUA BLUE Acquabios",
    brand: "Acquabios",
    subtitle: "Filtro de agua para punto de entrada (POE)",
    description:
      "Protección para tu casa. Filtro Acqua Blue Acquabios para punto de entrada: retén partículas, reduce cloro y aporta eficiencia bacteriológica en la red de agua de tu hogar. Incluye el primer cartucho de reposición gratis. Rosca 3/4\", compatible con cartucho push-in o roscado 1/2\". Certificación INMETRO.",
    priceBefore: 0,
    priceNow: 0,
    badge: "Cartucho gratis",
    badgeTone: "yellow",
    note: "Código: 1000-0065 · Incluye primer cartucho de reposición gratis",
    image: "/products/product-acqua-blue.png",
    images: [
      "/products/product-acqua-blue.png",
      "/products/product-acqua-blue-caja.png",
      "/products/product-acqua-blue-cartucho.png",
    ],
    tint: "blue",
    category: "filtracion",
    featured: true,
    inStock: true,
    tags: [
      { label: "Punto de entrada", icon: "bolt" },
      { label: "1200 L/h", icon: "bottles" },
      { label: "3/4\"", icon: "metal" },
    ],
    characteristics: [
      { label: "Código", value: "1000-0065" },
      { label: "Presión de trabajo", value: "19,6 a 588 kPa" },
      { label: "Temperatura", value: "5 °C a 50 °C" },
      { label: "Rosca", value: "3/4\"" },
      {
        label: "Cartucho",
        value: "Push-in o roscado 1/2\"",
      },
      {
        label: "Retención de partículas",
        value: "de ≥5 a <15 μm",
      },
      { label: "Tamaño físico", value: "9 3/4\"" },
      { label: "Flujo de agua", value: "1.200 litros por hora" },
    ],
    features: [
      "Protección para toda la casa (punto de entrada)",
      "Incluye primer cartucho de reposición gratis",
      "Reducción de cloro",
      "Retención de partículas",
      "Eficiencia bacteriológica",
      "Certificación INMETRO",
    ],
  },
];

export const specialOfferProducts = catalogProducts.filter((p) => p.featured);

export function getProductById(id: string): ProductOffer | undefined {
  return catalogProducts.find((p) => p.id === id);
}

export function getRelatedProducts(
  product: ProductOffer,
  limit = 4,
): ProductOffer[] {
  const sameCategory = catalogProducts.filter(
    (p) => p.id !== product.id && p.category === product.category,
  );
  if (sameCategory.length >= limit) {
    return sameCategory.slice(0, limit);
  }
  const extras = catalogProducts.filter(
    (p) =>
      p.id !== product.id &&
      p.category !== product.category &&
      !sameCategory.some((s) => s.id === p.id),
  );
  return [...sameCategory, ...extras].slice(0, limit);
}

export function getCategoryLabel(category: ProductOffer["category"]): string {
  return (
    PRODUCT_CATEGORIES.find((c) => c.id === category)?.label ?? category
  );
}
